from datetime import date, datetime

from departments.crypto import EncryptedString
from extensions import db  # Use absolute import for db


class Patient(db.Model):
    """Represents a patient."""

    __tablename__ = "patients"

    id = db.Column(db.Integer, primary_key=True)  # Internal database ID
    patient_id = db.Column(
        db.String(10), unique=True, nullable=False, index=True
    )  # Autogenerated unique patient number
    name = db.Column(db.String(100), nullable=False, index=True)  # e.g., 'John Doe'
    place_of_residence = db.Column(
        db.String(100), nullable=False
    )  # e.g., '123 Main St, City'
    sex = db.Column(db.String(10), nullable=False)  # e.g., 'Male', 'Female', 'Other'
    date_of_birth = db.Column(db.Date, nullable=False)
    marital_status = db.Column(
        db.String(20), nullable=False
    )  # e.g., 'Single', 'Married'
    blood_group = db.Column(db.String(5), nullable=True)  # e.g., 'A+', 'O-' (optional)
    contact = db.Column(
        db.String(15), nullable=False
    )  # Phone number, e.g., '+1234567890'
    next_of_kin = db.Column(db.String(100), nullable=False)  # e.g., 'Jane Doe'
    relationship_with_next_of_kin = db.Column(
        db.String(50), nullable=False
    )  # e.g., 'Spouse'
    next_of_kin_contact = db.Column(
        db.String(15), nullable=False
    )  # Next of kin's phone number
    national_id = db.Column(
        EncryptedString(500), nullable=True, index=False
    )  # National ID — encrypted at rest (Fernet AES-128-CBC)
    emergency_contact = db.Column(
        db.String(15), nullable=False
    )  # Emergency contact number
    date_registered = db.Column(
        db.DateTime, default=db.func.current_timestamp(), nullable=False
    )

    # Optional demographic / insurance fields
    insurance_provider = db.Column(db.String(100), nullable=True)
    insurance_policy_number = db.Column(db.String(100), nullable=True)
    occupation = db.Column(db.String(100), nullable=True)
    employer_name = db.Column(db.String(100), nullable=True)

    # Soft delete and audit metadata
    is_active = db.Column(db.Boolean, default=True, nullable=False)
    deleted_at = db.Column(db.DateTime, nullable=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    updated_at = db.Column(
        db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False
    )
    created_by = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=True)
    updated_by = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=True)

    def generate_patient_id(self):
        """Generate a unique patient ID with concurrency handling."""
        prefix = "P"
        with db.session.no_autoflush:  # Prevent premature flush
            last_patient = (
                Patient.query.order_by(Patient.id.desc()).with_for_update().first()
            )
            if last_patient and last_patient.patient_id.startswith(prefix):
                last_number = (
                    int(last_patient.patient_id[1:])
                    if last_patient.patient_id[1:].isdigit()
                    else 0
                )
            else:
                last_number = 0
            new_number = last_number + 1
            return f"{prefix}{new_number:04d}"  # Format as P0001, P0002, etc.

    @classmethod
    def active_patients(cls):
        """Return a query pre-filtered to active (non-deleted) patients."""
        return cls.query.filter_by(is_active=True)

    def soft_delete(self):
        """Mark this patient as deleted without removing the DB row."""
        self.is_active = False
        self.deleted_at = datetime.utcnow()

    def __repr__(self):
        return f"<Patient {self.patient_id}: {self.name}>"


class PatientIdentifier(db.Model):
    """Alternate patient identifiers (Birth Certificate, Passport, Emergency Temp ID, etc.)."""

    __tablename__ = "patient_identifiers"

    id = db.Column(db.Integer, primary_key=True)
    patient_id = db.Column(
        db.String(20), db.ForeignKey("patients.patient_id"), nullable=False
    )
    identifier_type = db.Column(
        db.String(50), nullable=False
    )  # e.g. Passport, Birth Notification, Refugee ID
    identifier_value = db.Column(db.String(100), nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)

    patient = db.relationship(
        "Patient", backref=db.backref("alternate_identifiers", lazy=True)
    )


class PatientMerge(db.Model):
    """Audit log of merged patient records."""

    __tablename__ = "patient_merges"

    id = db.Column(db.Integer, primary_key=True)
    source_patient_id = db.Column(db.String(20), nullable=False)
    target_patient_id = db.Column(db.String(20), nullable=False)
    merged_by = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
    merged_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    notes = db.Column(db.Text, nullable=True)


class PatientWaitingList(db.Model):
    """Represents a waiting list for patients."""

    __tablename__ = "patient_waiting_list"

    id = db.Column(
        db.Integer, primary_key=True, autoincrement=True
    )  # Primary key with autoincrement
    patient_id = db.Column(
        db.String(10), db.ForeignKey("patients.patient_id"), nullable=False
    )  # Foreign key to Patient
    seen = db.Column(
        db.Integer, default=0, nullable=False
    )  # Whether the patient has been seen (0 = No, 1 = Yes)

    # Define a relationship with Patient
    patient = db.relationship("Patient", backref="waiting_list", lazy="joined")

    def __repr__(self):
        return f"<PatientWaitingList Patient ID: {self.patient_id}, Seen: {self.seen}>"


class Clinic(db.Model):
    """Represents a clinic."""

    __tablename__ = "clinics"

    clinic_id = db.Column(db.Integer, primary_key=True)  # Primary key
    name = db.Column(db.String(100), nullable=False)  # Clinic name
    fee = db.Column(db.Float, nullable=False)  # Clinic fee

    def __repr__(self):
        return f"<Clinic {self.name}>"


class ClinicBooking(db.Model):
    """Represents a clinic booking with patient details and status."""

    __tablename__ = "clinic_bookings"

    id = db.Column(db.Integer, primary_key=True)  # Primary key
    patient_id = db.Column(
        db.String(10), db.ForeignKey("patients.patient_id"), nullable=False
    )  # Foreign key to patients
    clinic_id = db.Column(
        db.Integer, db.ForeignKey("clinics.clinic_id"), nullable=False
    )  # Foreign key to clinics
    created_on = db.Column(
        db.Date, default=date.today, nullable=False
    )  # Booking creation date
    clinic_date = db.Column(
        db.Date, nullable=False
    )  # Date the patient is supposed to come
    seen = db.Column(
        db.Integer, default=0, nullable=False
    )  # Status: 0 = Not seen, 1 = Seen
    receipt_number = db.Column(
        db.String(255), nullable=True
    )  # Added for billing integration

    # Relationships
    patient = db.relationship(
        "Patient", backref="bookings", lazy=True
    )  # Link to Patient
    clinic = db.relationship("Clinic", backref="bookings", lazy=True)  # Link to Clinic

    def __repr__(self):
        return f"<ClinicBooking {self.id}>"


class PatientAllergy(db.Model):
    """Structured Patient Allergy Registry."""

    __tablename__ = "patient_allergies"

    id = db.Column(db.Integer, primary_key=True)
    patient_id = db.Column(
        db.String(20), db.ForeignKey("patients.patient_id"), nullable=False, index=True
    )
    allergen = db.Column(
        db.String(100), nullable=False, index=True
    )  # e.g. Penicillin, Sulfa, Aspirin
    category = db.Column(
        db.String(50), nullable=False, default="DRUG"
    )  # DRUG, FOOD, ENVIRONMENTAL, OTHER
    reaction = db.Column(db.String(255), nullable=True)
    severity = db.Column(
        db.String(20), nullable=False, default="MODERATE"
    )  # MILD, MODERATE, SEVERE, ANAPHYLACTIC
    date_recorded = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    recorded_by = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=True)

    patient = db.relationship("Patient", backref=db.backref("allergies", lazy=True))

    def __repr__(self):
        return f"<PatientAllergy {self.allergen} ({self.severity}) for Patient {self.patient_id}>"


class PatientProblem(db.Model):
    """Active Clinical Problem List per patient."""

    __tablename__ = "patient_problems"

    id = db.Column(db.Integer, primary_key=True)
    patient_id = db.Column(
        db.String(20), db.ForeignKey("patients.patient_id"), nullable=False, index=True
    )
    icd10_code = db.Column(db.String(20), nullable=True, index=True)  # e.g., 'E11.9'
    description = db.Column(db.String(255), nullable=False)
    status = db.Column(
        db.String(20), nullable=False, default="ACTIVE"
    )  # ACTIVE, RESOLVED, CHRONIC
    onset_date = db.Column(db.Date, nullable=True)
    resolved_date = db.Column(db.Date, nullable=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    created_by = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=True)

    patient = db.relationship("Patient", backref=db.backref("problems", lazy=True))

    def __repr__(self):
        return f"<PatientProblem {self.description} [{self.status}] for Patient {self.patient_id}>"
