# Model configuration
model_name: microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract
fallback_model_name: distilbert-base-uncased
model_version: 1.0.0
device: cpu
max_length: 512
batch_size: 16
embedding_dim: 768
similarity_threshold: 0.9
confidence_threshold: 0.85

# Hugging Face optional auth token (uncomment if needed)
# hf_token: your_huggingface_token_here

# Database configuration
mongodb_uri: mongodb://127.0.0.1:27017/
redis_url: redis://localhost:6379

# Entrez
entrez_email: mathunjoroge@gmail.com

# Logging configuration
log_level: DEBUG
log_file: logs/clinical_ai.log
error_log_file: logs/error_log.txt
max_log_size: 10485760  # 10MB
backup_count: 5
