<?php 
require_once('../main/auth.php');
?>
<!DOCTYPE html>
<html>
<title>register patient</title>
<?php 
include('../header.php');
?>
</head>
<header class="header clearfix" style="background-color: #3786d6;">
</button>
<?php include('../main/nav.php'); ?>   
</header><?php include('side.php'); ?>
   
<div class="jumbotron" style="background: #95CAFC;">  

<script>
$( function() {
$( "#mydate" ).datepicker({
yearRange: "-100:+0",
changeMonth: true,
changeYear: true
});
} );

</script>
 
<?php
$a=$_GET['attempt'];
if ($a==0) { echo "";
?>
<?php
$end = date('Y-m-d', strtotime('-5 years'));
} ?>
<?php 
include ('../connect.php');
$result = $db->prepare("SELECT * FROM patients ORDER BY id DESC LIMIT 1");
$result->execute();
$result->execute();
for($i=0; $row = $result->fetch(); $i++){
$req= substr($row['opno'],-4);
}
if ($req==date('Y')){
$a='/'.$req;
$result = $db->prepare("SELECT * FROM patients WHERE opno LIKE '%$a%'");
$result->execute();
$patient = $result->rowcount()+1;
$patient_number=$patient."/".date('Y');
}
if ($req!==date('Y')){
$patient_number='1'."/".date('Y');
}
?>
<div class="container" style="">
<?php
$a=$_GET['attempt']; 
if ($a==2) {

?>
<p class="alert alert-success h6" style="float:left;font-size:1.5rem;" > <?php echo $_GET['name']; ?> has been allocated a bed.</p><?php } ?>
<?php
$a=$_GET['attempt']; 
if ($a==3) {

?>
<p class="alert alert-success h6"  style="float:left;font-size:1.5rem;"> <?php echo $_GET['name']; ?> data has been saved.</p><?php } ?>
</div>

<h3>register patient</h3>
<style type="text/css">
#register{
border-style: inset;  background-image: url('../images/bg.jpg');
text-align:center;

}
@media only screen and (max-width: 600px) {
#register {
margin-left: 0%;
}
}
</style>
<div class="container" id="register" >
<form action="save_walk_in.php" method="post">
<div class="form-row">
<div class="form-group col-md-6">
<label for="name">patient name</label>
<input type="text" class="form-control" name="name"  placeholder="patient name" required="true" />
</div>
<div class="form-group col-md-6">
<label for="inputtext4">date of birth</label>
<input type="text" id="mydate" class="form-control" name="age" placeholder="date of birth in dd-mm-yyyy" autocomplete="off" required>
</div>
<div class="form-group col-md-6">

<label for="inputtext4">sex</label>
<select name="sex" class="form-control" required><option>select sex</option><option >male</option><option >female</option></select>
</div>

<div class="form-group col-md-6">
<label for="inputPassword4">Patient number(autogenerated)</label>
<input type="text" class="form-control" name="number" value="<?php echo mt_rand(10000000, 99999999); ?>"  readonly>
</div>

<div class="form-group col-md-6">
<label for="inputPassword4">select lab tests to be paid</label></br>
<select id="fee" class="selectpicker form-control" data-live-search="true"   title="select lab tests"  name="lab[]"  multiple/>
<option value="">-- Select payable fees--</option><?php 
include ('../connect.php');
$result = $db->prepare("SELECT * FROM lab_tests");
$result->execute();
for($i=0; $row = $result->fetch(); $i++){
echo "<option value=".$row['id'].">".$row['name']."</option>";
}

?>      
</select>
</div>

<div class="form-group col-md-6">
<label for="inputPassword4">select fees to be paid</label></br>
<select id="fee" class="selectpicker form-control"  title="select fees" data-live-search="true"  name="fees[]"  multiple/>
<option value="">-- Select payable fees--</option><?php 
include ('../connect.php');
$result = $db->prepare("SELECT * FROM fees");
$result->execute();
for($i=0; $row = $result->fetch(); $i++){
echo "<option value=".$row['fees_id'].">".$row['fees_name']."</option>";
}

?>      
</select>
</div>
</div>
<button class="btn btn-success btn-large" style="width: 80%; margin-left:10%;">save</button></form>

</div></div>
</div></div>
</div></div>

</body>
</html>