import uuid
from datetime import datetime, timezone

from extensions import db


class DeviceRegistry(db.Model):
    """
    Tracks devices that are authorized to perform offline sync.
    Essential for identifying the source of offline changes and revoking access.
    """

    __tablename__ = "device_registry"

    id = db.Column(db.String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    device_fingerprint = db.Column(db.String(255), nullable=False, unique=True)
    user_id = db.Column(db.Integer, nullable=False, index=True)

    # e.g., "Chrome PWA on Windows", "iPad Safari"
    device_name = db.Column(db.String(100), nullable=True)

    last_sync_at = db.Column(db.DateTime(timezone=True), nullable=True)
    is_active = db.Column(db.Boolean, default=True, nullable=False)

    registered_at = db.Column(
        db.DateTime(timezone=True), default=lambda: datetime.now(timezone.utc)
    )


class SyncQueue(db.Model):
    """
    Stores offline mutations (CREATE, UPDATE, DELETE) generated by the PWA
    while the device was disconnected from the network.
    """

    __tablename__ = "sync_queue"

    id = db.Column(db.String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    device_id = db.Column(
        db.String(36), db.ForeignKey("device_registry.id"), nullable=False, index=True
    )

    # e.g., "Patient", "Vitals", "SOAPNote"
    entity_type = db.Column(db.String(50), nullable=False)
    entity_id = db.Column(db.String(36), nullable=False)

    # CREATE, UPDATE, DELETE
    mutation_type = db.Column(db.String(20), nullable=False)

    # JSON string of the payload
    payload_json = db.Column(db.Text, nullable=False)

    # Timestamp generated by the CLIENT device
    client_timestamp = db.Column(db.DateTime(timezone=True), nullable=False)

    processed = db.Column(db.Boolean, default=False, nullable=False, index=True)

    queued_at = db.Column(
        db.DateTime(timezone=True), default=lambda: datetime.now(timezone.utc)
    )


class SyncConflict(db.Model):
    """
    Logs data collisions where the server record was modified by another user
    while this device was offline.
    """

    __tablename__ = "sync_conflicts"

    id = db.Column(db.String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    queue_id = db.Column(db.String(36), db.ForeignKey("sync_queue.id"), nullable=False)

    # The state of the record on the server at the time of conflict
    server_payload_json = db.Column(db.Text, nullable=True)

    # PENDING_RESOLUTION, SERVER_WON, CLIENT_WON, MANUAL_MERGE
    resolution_status = db.Column(
        db.String(20), nullable=False, default="PENDING_RESOLUTION"
    )

    detected_at = db.Column(
        db.DateTime(timezone=True), default=lambda: datetime.now(timezone.utc)
    )
    resolved_at = db.Column(db.DateTime(timezone=True), nullable=True)
