"""add Encounter model to bridge visits with clinical and billing data

Revision ID: 08d341f1843b
Revises: 432fa04c5638
Create Date: 2026-09-08 23:06:29.007700

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '08d341f1843b'
down_revision = '432fa04c5638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encounters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=20), nullable=False),
    sa.Column('appointment_id', sa.String(length=36), nullable=True),
    sa.Column('clinic_booking_id', sa.Integer(), nullable=True),
    sa.Column('encounter_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider_id', sa.String(length=50), nullable=True),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['clinic_booking_id'], ['clinic_bookings.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('encounters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_encounters_appointment_id'), ['appointment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_encounters_clinic_booking_id'), ['clinic_booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_encounters_encounter_id'), ['encounter_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_encounters_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_encounters_provider_id'), ['provider_id'], unique=False)

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('provider_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('provider_id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('patient_id',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('encounters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_encounters_provider_id'))
        batch_op.drop_index(batch_op.f('ix_encounters_patient_id'))
        batch_op.drop_index(batch_op.f('ix_encounters_encounter_id'))
        batch_op.drop_index(batch_op.f('ix_encounters_clinic_booking_id'))
        batch_op.drop_index(batch_op.f('ix_encounters_appointment_id'))

    op.drop_table('encounters')
    # ### end Alembic commands ###
