"""Add Consent MVP for Phase 1

Revision ID: 0f5def37a442
Revises: 973086681bee
Create Date: 2026-09-07 11:51:41.601658

"""
import sqlalchemy as sa
from alembic import op

import departments.crypto

# revision identifiers, used by Alembic.
revision = '0f5def37a442'
down_revision = '973086681bee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('consent_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.String(length=100), nullable=True),
    sa.Column('revocation_reason', sa.Text(), nullable=True),
    sa.Column('document_reference', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consents_patient_id'), ['patient_id'], unique=False)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('national_id',
               existing_type=sa.VARCHAR(length=50),
               type_=departments.crypto.EncryptedString(length=500),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_patients_national_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_national_id'), ['national_id'], unique=True)
        batch_op.alter_column('national_id',
               existing_type=departments.crypto.EncryptedString(length=500),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consents_patient_id'))

    op.drop_table('consents')
    # ### end Alembic commands ###
