"""create missing tables from models

Revision ID: 2905388615a1
Revises: ebed81b14204
Create Date: 2026-09-07 21:14:15.020379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2905388615a1'
down_revision = 'ebed81b14204'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anc_visits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('visit_number', sa.Integer(), nullable=False),
    sa.Column('gestation_weeks', sa.Integer(), nullable=False),
    sa.Column('high_risk_factors', sa.Text(), nullable=True),
    sa.Column('next_appointment_date', sa.Date(), nullable=True),
    sa.Column('visit_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anc_visits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anc_visits_patient_id'), ['patient_id'], unique=False)

    op.create_table('claim_submissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('insurance_scheme_id', sa.Integer(), nullable=True),
    sa.Column('billed_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('approved_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payer_reference', sa.String(length=100), nullable=True),
    sa.Column('primary_diagnosis_icd10', sa.String(length=10), nullable=True),
    sa.Column('secondary_diagnosis_icd10', sa.String(length=10), nullable=True),
    sa.Column('service_start_date', sa.Date(), nullable=False),
    sa.Column('service_end_date', sa.Date(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claim_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claim_submissions_patient_id'), ['patient_id'], unique=False)

    op.create_table('immunization_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('child_patient_id', sa.Integer(), nullable=False),
    sa.Column('vaccine_name', sa.String(length=100), nullable=False),
    sa.Column('dose_number', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=50), nullable=True),
    sa.Column('administered_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('immunization_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_immunization_records_child_patient_id'), ['child_patient_id'], unique=False)

    op.create_table('mpesa_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('merchant_request_id', sa.String(length=50), nullable=True),
    sa.Column('checkout_request_id', sa.String(length=50), nullable=True),
    sa.Column('mpesa_receipt_number', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result_desc', sa.Text(), nullable=True),
    sa.Column('initiated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mpesa_receipt_number')
    )
    with op.batch_alter_table('mpesa_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mpesa_transactions_checkout_request_id'), ['checkout_request_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_mpesa_transactions_reference'), ['reference'], unique=False)

    op.create_table('payment_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('total_debt_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('installment_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('number_of_installments', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('preferred_payment_method', sa.String(length=30), nullable=True),
    sa.Column('next_payment_due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_plans_patient_id'), ['patient_id'], unique=False)

    op.create_table('pre_authorizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('insurance_scheme_id', sa.Integer(), nullable=False),
    sa.Column('procedure_code', sa.String(length=50), nullable=False),
    sa.Column('procedure_description', sa.Text(), nullable=True),
    sa.Column('estimated_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('authorization_number', sa.String(length=100), nullable=True),
    sa.Column('clinical_justification', sa.Text(), nullable=True),
    sa.Column('denial_reason', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pre_authorizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pre_authorizations_patient_id'), ['patient_id'], unique=False)

    op.create_table('safety_alert_overrides',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('clinician_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('alert_message', sa.Text(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('overridden_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('safety_alert_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_safety_alert_overrides_patient_id'), ['patient_id'], unique=False)

    op.create_table('claim_denials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('claim_id', sa.String(length=36), nullable=False),
    sa.Column('denial_code', sa.String(length=50), nullable=False),
    sa.Column('denial_reason', sa.Text(), nullable=False),
    sa.Column('appeal_status', sa.String(length=30), nullable=False),
    sa.Column('appeal_justification', sa.Text(), nullable=True),
    sa.Column('appeal_submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('appeal_resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('denied_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claim_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claim_denials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claim_denials_claim_id'), ['claim_id'], unique=False)

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_user_id'))

    with op.batch_alter_table('billing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_charge_id'))

    with op.batch_alter_table('custom_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom_rule_employee_id'))

    with op.batch_alter_table('drugs_bill', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drugs_bill_drug_id'))

    with op.batch_alter_table('medication_admin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medication_admin_recorded_by'))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_receiver_id'))
        batch_op.drop_index(batch_op.f('ix_messages_sender_id'))

    with op.batch_alter_table('mortuary_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mortuary_data_recorded_by'))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_receiver_id'))

    with op.batch_alter_table('partogram', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partogram_recorded_by'))

    with op.batch_alter_table('patient_insurance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_insurance_verified_by'))

    with op.batch_alter_table('regimen_drug_association', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regimen_drug_association_drug_id'))
        batch_op.drop_index(batch_op.f('ix_regimen_drug_association_regimen_id'))

    with op.batch_alter_table('theatre_list', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_theatre_list_procedure_id'))

    with op.batch_alter_table('vitals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vitals_nurse_id'))

    with op.batch_alter_table('ward_bed_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ward_bed_history_ward_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ward_bed_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ward_bed_history_ward_id'), ['ward_id'], unique=False)

    with op.batch_alter_table('vitals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vitals_nurse_id'), ['nurse_id'], unique=False)

    with op.batch_alter_table('theatre_list', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_theatre_list_procedure_id'), ['procedure_id'], unique=False)

    with op.batch_alter_table('regimen_drug_association', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regimen_drug_association_regimen_id'), ['regimen_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_regimen_drug_association_drug_id'), ['drug_id'], unique=False)

    with op.batch_alter_table('patient_insurance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_insurance_verified_by'), ['verified_by'], unique=False)

    with op.batch_alter_table('partogram', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partogram_recorded_by'), ['recorded_by'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_receiver_id'), ['receiver_id'], unique=False)

    with op.batch_alter_table('mortuary_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mortuary_data_recorded_by'), ['recorded_by'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_receiver_id'), ['receiver_id'], unique=False)

    with op.batch_alter_table('medication_admin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medication_admin_recorded_by'), ['recorded_by'], unique=False)

    with op.batch_alter_table('drugs_bill', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drugs_bill_drug_id'), ['drug_id'], unique=False)

    with op.batch_alter_table('custom_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_rule_employee_id'), ['employee_id'], unique=False)

    with op.batch_alter_table('billing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_charge_id'), ['charge_id'], unique=False)

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('claim_denials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claim_denials_claim_id'))

    op.drop_table('claim_denials')
    with op.batch_alter_table('safety_alert_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_safety_alert_overrides_patient_id'))

    op.drop_table('safety_alert_overrides')
    with op.batch_alter_table('pre_authorizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pre_authorizations_patient_id'))

    op.drop_table('pre_authorizations')
    with op.batch_alter_table('payment_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_plans_patient_id'))

    op.drop_table('payment_plans')
    with op.batch_alter_table('mpesa_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mpesa_transactions_reference'))
        batch_op.drop_index(batch_op.f('ix_mpesa_transactions_checkout_request_id'))

    op.drop_table('mpesa_transactions')
    with op.batch_alter_table('immunization_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_immunization_records_child_patient_id'))

    op.drop_table('immunization_records')
    with op.batch_alter_table('claim_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claim_submissions_patient_id'))

    op.drop_table('claim_submissions')
    with op.batch_alter_table('anc_visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anc_visits_patient_id'))

    op.drop_table('anc_visits')
    # ### end Alembic commands ###
