"""create missing tables from models

Revision ID: 2905388615a1
Revises: ebed81b14204
Create Date: 2026-09-07 21:14:15.020379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2905388615a1'
down_revision = 'ebed81b14204'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()

    if 'anc_visits' not in tables:
        op.create_table('anc_visits',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('patient_id', sa.Integer(), nullable=False),
        sa.Column('visit_number', sa.Integer(), nullable=False),
        sa.Column('gestation_weeks', sa.Integer(), nullable=False),
        sa.Column('high_risk_factors', sa.Text(), nullable=True),
        sa.Column('next_appointment_date', sa.Date(), nullable=True),
        sa.Column('visit_date', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('anc_visits', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_anc_visits_patient_id'), ['patient_id'], unique=False)

    if 'claim_submissions' not in tables:
        op.create_table('claim_submissions',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('patient_id', sa.Integer(), nullable=False),
        sa.Column('insurance_scheme_id', sa.Integer(), nullable=True),
        sa.Column('billed_amount', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('approved_amount', sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('payer_reference', sa.String(length=100), nullable=True),
        sa.Column('primary_diagnosis_icd10', sa.String(length=10), nullable=True),
        sa.Column('secondary_diagnosis_icd10', sa.String(length=10), nullable=True),
        sa.Column('service_start_date', sa.Date(), nullable=False),
        sa.Column('service_end_date', sa.Date(), nullable=False),
        sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('claim_submissions', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_claim_submissions_patient_id'), ['patient_id'], unique=False)

    if 'immunization_records' not in tables:
        op.create_table('immunization_records',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('child_patient_id', sa.Integer(), nullable=False),
        sa.Column('vaccine_name', sa.String(length=100), nullable=False),
        sa.Column('dose_number', sa.Integer(), nullable=False),
        sa.Column('batch_number', sa.String(length=50), nullable=True),
        sa.Column('administered_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('immunization_records', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_immunization_records_child_patient_id'), ['child_patient_id'], unique=False)

    if 'mpesa_transactions' not in tables:
        op.create_table('mpesa_transactions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('reference', sa.String(length=50), nullable=False),
        sa.Column('phone_number', sa.String(length=15), nullable=False),
        sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('merchant_request_id', sa.String(length=50), nullable=True),
        sa.Column('checkout_request_id', sa.String(length=50), nullable=True),
        sa.Column('mpesa_receipt_number', sa.String(length=50), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('result_desc', sa.Text(), nullable=True),
        sa.Column('initiated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('mpesa_receipt_number')
        )
        with op.batch_alter_table('mpesa_transactions', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_mpesa_transactions_checkout_request_id'), ['checkout_request_id'], unique=True)
            batch_op.create_index(batch_op.f('ix_mpesa_transactions_reference'), ['reference'], unique=False)

    if 'payment_plans' not in tables:
        op.create_table('payment_plans',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('patient_id', sa.Integer(), nullable=False),
        sa.Column('total_debt_amount', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('installment_amount', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('number_of_installments', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('preferred_payment_method', sa.String(length=30), nullable=True),
        sa.Column('next_payment_due_date', sa.Date(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('payment_plans', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_payment_plans_patient_id'), ['patient_id'], unique=False)

    if 'pre_authorizations' not in tables:
        op.create_table('pre_authorizations',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('patient_id', sa.Integer(), nullable=False),
        sa.Column('insurance_scheme_id', sa.Integer(), nullable=False),
        sa.Column('procedure_code', sa.String(length=50), nullable=False),
        sa.Column('procedure_description', sa.Text(), nullable=True),
        sa.Column('estimated_amount', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('authorization_number', sa.String(length=100), nullable=True),
        sa.Column('clinical_justification', sa.Text(), nullable=True),
        sa.Column('denial_reason', sa.Text(), nullable=True),
        sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('pre_authorizations', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_pre_authorizations_patient_id'), ['patient_id'], unique=False)

    if 'safety_alert_overrides' not in tables:
        op.create_table('safety_alert_overrides',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('patient_id', sa.Integer(), nullable=False),
        sa.Column('clinician_id', sa.Integer(), nullable=False),
        sa.Column('alert_type', sa.String(length=50), nullable=False),
        sa.Column('alert_message', sa.Text(), nullable=False),
        sa.Column('justification', sa.Text(), nullable=False),
        sa.Column('overridden_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('safety_alert_overrides', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_safety_alert_overrides_patient_id'), ['patient_id'], unique=False)

    if 'claim_denials' not in tables:
        op.create_table('claim_denials',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('claim_id', sa.String(length=36), nullable=False),
        sa.Column('denial_code', sa.String(length=50), nullable=False),
        sa.Column('denial_reason', sa.Text(), nullable=False),
        sa.Column('appeal_status', sa.String(length=30), nullable=False),
        sa.Column('appeal_justification', sa.Text(), nullable=True),
        sa.Column('appeal_submitted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('appeal_resolved_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('denied_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['claim_id'], ['claim_submissions.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('claim_denials', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_claim_denials_claim_id'), ['claim_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()

    if 'claim_denials' in tables:
        with op.batch_alter_table('claim_denials', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_claim_denials_claim_id'))
        op.drop_table('claim_denials')
    if 'safety_alert_overrides' in tables:
        with op.batch_alter_table('safety_alert_overrides', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_safety_alert_overrides_patient_id'))
        op.drop_table('safety_alert_overrides')
    if 'pre_authorizations' in tables:
        with op.batch_alter_table('pre_authorizations', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_pre_authorizations_patient_id'))
        op.drop_table('pre_authorizations')
    if 'payment_plans' in tables:
        with op.batch_alter_table('payment_plans', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_payment_plans_patient_id'))
        op.drop_table('payment_plans')
    if 'mpesa_transactions' in tables:
        with op.batch_alter_table('mpesa_transactions', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_mpesa_transactions_reference'))
            batch_op.drop_index(batch_op.f('ix_mpesa_transactions_checkout_request_id'))
        op.drop_table('mpesa_transactions')
    if 'immunization_records' in tables:
        with op.batch_alter_table('immunization_records', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_immunization_records_child_patient_id'))
        op.drop_table('immunization_records')
    if 'claim_submissions' in tables:
        with op.batch_alter_table('claim_submissions', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_claim_submissions_patient_id'))
        op.drop_table('claim_submissions')
    if 'anc_visits' in tables:
        with op.batch_alter_table('anc_visits', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_anc_visits_patient_id'))
        op.drop_table('anc_visits')
    # ### end Alembic commands ###
