"""add_vote_heads_and_transfer_orders

Revision ID: 3059ae209032
Revises: 3d50aaf51986
Create Date: 2026-09-06 17:30:15.187372

"""
from alembic import op
import sqlalchemy as sa
import departments.crypto


# revision identifiers, used by Alembic.
revision = '3059ae209032'
down_revision = '3d50aaf51986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote_heads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('financial_year', sa.String(length=20), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('encumbered_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('spent_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vote_heads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vote_heads_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_vote_heads_department'), ['department'], unique=False)

    op.create_table('transfer_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_number', sa.String(length=50), nullable=False),
    sa.Column('source_facility_id', sa.Integer(), nullable=False),
    sa.Column('target_facility_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('dispatched_by_id', sa.Integer(), nullable=True),
    sa.Column('received_by_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dispatched_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['received_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['target_facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transfer_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transfer_orders_source_facility_id'), ['source_facility_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfer_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfer_orders_target_facility_id'), ['target_facility_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfer_orders_transfer_number'), ['transfer_number'], unique=True)

    op.create_table('transfer_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('drug_id', sa.Integer(), nullable=True),
    sa.Column('non_pharm_item_id', sa.Integer(), nullable=True),
    sa.Column('quantity_requested', sa.Integer(), nullable=False),
    sa.Column('quantity_dispatched', sa.Integer(), nullable=False),
    sa.Column('quantity_received', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=50), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.ForeignKeyConstraint(['non_pharm_item_id'], ['non_pharm_items.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfer_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transfer_order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transfer_order_items_drug_id'), ['drug_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfer_order_items_non_pharm_item_id'), ['non_pharm_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfer_order_items_transfer_id'), ['transfer_id'], unique=False)

    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vote_head_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_purchase_order_items_vote_head_id'), ['vote_head_id'], unique=False)
        batch_op.create_foreign_key(None, 'vote_heads', ['vote_head_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_purchase_order_items_vote_head_id'))
        batch_op.drop_column('vote_head_id')

    with op.batch_alter_table('transfer_order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transfer_order_items_transfer_id'))
        batch_op.drop_index(batch_op.f('ix_transfer_order_items_non_pharm_item_id'))
        batch_op.drop_index(batch_op.f('ix_transfer_order_items_drug_id'))

    op.drop_table('transfer_order_items')
    with op.batch_alter_table('transfer_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transfer_orders_transfer_number'))
        batch_op.drop_index(batch_op.f('ix_transfer_orders_target_facility_id'))
        batch_op.drop_index(batch_op.f('ix_transfer_orders_status'))
        batch_op.drop_index(batch_op.f('ix_transfer_orders_source_facility_id'))

    op.drop_table('transfer_orders')
    with op.batch_alter_table('vote_heads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vote_heads_department'))
        batch_op.drop_index(batch_op.f('ix_vote_heads_code'))

    op.drop_table('vote_heads')
    # ### end Alembic commands ###

