"""add master_clinical_regimens table for NASCOP & NTLD-P

Revision ID: 315d18d94f09
Revises: f2a1cd436c77
Create Date: 2026-09-17 17:27:48.318229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '315d18d94f09'
down_revision = 'f2a1cd436c77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_clinical_regimens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('program_domain', sa.String(length=20), nullable=False),
    sa.Column('nascop_ntldp_code', sa.String(length=30), nullable=False),
    sa.Column('regimen_acronym', sa.String(length=50), nullable=False),
    sa.Column('line_tier', sa.String(length=30), nullable=False),
    sa.Column('target_population', sa.String(length=100), nullable=False),
    sa.Column('drug_components', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('master_clinical_regimens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_master_clinical_regimens_nascop_ntldp_code'), ['nascop_ntldp_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_master_clinical_regimens_program_domain'), ['program_domain'], unique=False)

    with op.batch_alter_table('moh_729b_arv_fcdrr_monthly', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('moh_731_arv_regimen_patients_monthly', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moh_731_arv_regimen_patients_monthly', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('moh_729b_arv_fcdrr_monthly', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('master_clinical_regimens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_clinical_regimens_program_domain'))
        batch_op.drop_index(batch_op.f('ix_master_clinical_regimens_nascop_ntldp_code'))

    op.drop_table('master_clinical_regimens')
    # ### end Alembic commands ###
