"""add_facility_stock_movement_and_po_sod_columns

Revision ID: 3d50aaf51986
Revises: c3f8a1d92e74
Create Date: 2026-09-06 16:57:09.568659

"""
from alembic import op
import sqlalchemy as sa
import departments.crypto


# revision identifiers, used by Alembic.
revision = '3d50aaf51986'
down_revision = 'c3f8a1d92e74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('facility_code', sa.String(length=50), nullable=True),
    sa.Column('facility_type', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('contact_email', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_self', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('facilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facilities_facility_code'), ['facility_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_facilities_is_self'), ['is_self'], unique=False)
        batch_op.create_index(batch_op.f('ix_facilities_name'), ['name'], unique=False)

    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('movement_type', sa.String(length=30), nullable=False),
    sa.Column('quantity_delta', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.create_index('idx_sm_item', ['item_type', 'item_id'], unique=False)
        batch_op.create_index('idx_sm_ref', ['reference_type', 'reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_item_type'), ['item_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_movement_type'), ['movement_type'], unique=False)

    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_type', sa.String(length=20), nullable=False, server_default='DRUG'))
        batch_op.add_column(sa.Column('non_pharm_item_id', sa.Integer(), nullable=True))
        batch_op.alter_column('drug_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_purchase_order_items_non_pharm_item_id'), ['non_pharm_item_id'], unique=False)
        batch_op.create_foreign_key(None, 'non_pharm_items', ['non_pharm_item_id'], ['id'])

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('received_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sod_warning', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.create_foreign_key(None, 'users', ['received_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['created_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['approved_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sod_warning')
        batch_op.drop_column('received_by_id')
        batch_op.drop_column('approved_by_id')
        batch_op.drop_column('created_by_id')

    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_purchase_order_items_non_pharm_item_id'))
        batch_op.alter_column('drug_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('non_pharm_item_id')
        batch_op.drop_column('item_type')

    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_movements_movement_type'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_item_type'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_item_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_created_at'))
        batch_op.drop_index('idx_sm_ref')
        batch_op.drop_index('idx_sm_item')

    op.drop_table('stock_movements')
    with op.batch_alter_table('facilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facilities_name'))
        batch_op.drop_index(batch_op.f('ix_facilities_is_self'))
        batch_op.drop_index(batch_op.f('ix_facilities_facility_code'))

    op.drop_table('facilities')
    # ### end Alembic commands ###

