"""add password reset fields to PatientUser

Revision ID: 432fa04c5638
Revises: 4753b4b4f373
Create Date: 2026-09-08 12:33:57.287791

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '432fa04c5638'
down_revision = '4753b4b4f373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expiry', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_patient_users_reset_token'), ['reset_token'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_users_reset_token'))
        batch_op.drop_column('reset_token_expiry')
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###
