"""add pre_bun post_bun spkt_v to dialysis_sessions

Revision ID: 4c22bf975de7
Revises: e5f6a7b8c9d0
Create Date: 2026-09-20 11:51:45.384548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c22bf975de7'
down_revision = 'e5f6a7b8c9d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dialysis_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pre_bun', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('post_bun', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('spkt_v', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dialysis_sessions', schema=None) as batch_op:
        batch_op.drop_column('spkt_v')
        batch_op.drop_column('post_bun')
        batch_op.drop_column('pre_bun')

    # ### end Alembic commands ###

