"""phase3_add_controlled_drug_register_v3

Revision ID: 4fe1bd4f2453
Revises: 98b602e8fcea
Create Date: 2026-09-11 10:42:09.815688

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4fe1bd4f2453'
down_revision = '98b602e8fcea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drugs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_controlled', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('schedule_class', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drugs', schema=None) as batch_op:
        batch_op.drop_column('schedule_class')
        batch_op.drop_column('is_controlled')

    # ### end Alembic commands ###
