"""phase2_add_facility_id_and_rls

Revision ID: 663aab59f66e
Revises: 4fe1bd4f2453
Create Date: 2026-09-11 14:06:23.581356

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '663aab59f66e'
down_revision = '4fe1bd4f2453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encounters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facility_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_encounters_facility_id'), ['facility_id'], unique=False)
        batch_op.create_foreign_key(None, 'facilities', ['facility_id'], ['id'])

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facility_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_invoices_facility_id'), ['facility_id'], unique=False)
        batch_op.create_foreign_key(None, 'facilities', ['facility_id'], ['id'])

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facility_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_patients_facility_id'), ['facility_id'], unique=False)
        batch_op.create_foreign_key(None, 'facilities', ['facility_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facility_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_facility_id'), ['facility_id'], unique=False)
        batch_op.create_foreign_key(None, 'facilities', ['facility_id'], ['id'])

    # ### end Alembic commands ###



    # Backfill existing records with the home facility ID
    op.execute("""
        UPDATE patients SET facility_id = (SELECT id FROM facilities WHERE is_self = TRUE LIMIT 1) WHERE facility_id IS NULL;
        UPDATE encounters SET facility_id = (SELECT id FROM facilities WHERE is_self = TRUE LIMIT 1) WHERE facility_id IS NULL;
        UPDATE users SET facility_id = (SELECT id FROM facilities WHERE is_self = TRUE LIMIT 1) WHERE facility_id IS NULL;
        UPDATE invoices SET facility_id = (SELECT id FROM facilities WHERE is_self = TRUE LIMIT 1) WHERE facility_id IS NULL;
    """)

    # Enable Row Level Security
    for table in ['patients', 'encounters', 'users', 'invoices']:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY;")

        # Policy: Allow if session var is unset (tests/background) OR matches facility_id
        policy_sql = f"""
            CREATE POLICY tenant_isolation_{table} ON {table}
            USING (
                current_setting('app.current_facility_id', true) IS NULL
                OR current_setting('app.current_facility_id', true) = ''
                OR facility_id = NULLIF(current_setting('app.current_facility_id', true), '')::INTEGER
            );
        """
        op.execute(policy_sql)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_facility_id'))
        batch_op.drop_column('facility_id')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_patients_facility_id'))
        batch_op.drop_column('facility_id')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_invoices_facility_id'))
        batch_op.drop_column('facility_id')

    with op.batch_alter_table('encounters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_encounters_facility_id'))
        batch_op.drop_column('facility_id')

    # ### end Alembic commands ###
