"""add stock_takes and stock_take_items tables

Revision ID: 973086681bee
Revises: fc41aabfed4a
Create Date: 2026-09-06 20:18:51.477844

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '973086681bee'
down_revision = 'fc41aabfed4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_takes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('take_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('total_items_counted', sa.Integer(), nullable=False),
    sa.Column('total_variance_count', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_takes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_takes_take_number'), ['take_number'], unique=True)

    op.create_table('stock_take_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_take_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('drug_id', sa.Integer(), nullable=True),
    sa.Column('non_pharm_item_id', sa.Integer(), nullable=True),
    sa.Column('book_quantity', sa.Integer(), nullable=False),
    sa.Column('physical_quantity', sa.Integer(), nullable=False),
    sa.Column('variance', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.ForeignKeyConstraint(['non_pharm_item_id'], ['non_pharm_items.id'], ),
    sa.ForeignKeyConstraint(['stock_take_id'], ['stock_takes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_take_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_take_items_drug_id'), ['drug_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_take_items_non_pharm_item_id'), ['non_pharm_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_take_items_stock_take_id'), ['stock_take_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('stock_take_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_take_items_stock_take_id'))
        batch_op.drop_index(batch_op.f('ix_stock_take_items_non_pharm_item_id'))
        batch_op.drop_index(batch_op.f('ix_stock_take_items_drug_id'))

    op.drop_table('stock_take_items')
    with op.batch_alter_table('stock_takes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_takes_take_number'))

    op.drop_table('stock_takes')
    # ### end Alembic commands ###
