"""Add source tracking columns to InvoiceLineItem for billing sync

Revision ID: a84b0e726071
Revises: 2905388615a1
Create Date: 2026-09-07 22:27:13.968180

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a84b0e726071'
down_revision = '2905388615a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_line_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_table', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('source_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_invoice_line_item_source', ['source_table', 'source_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_line_items', schema=None) as batch_op:
        batch_op.drop_constraint('uq_invoice_line_item_source', type_='unique')
        batch_op.drop_column('source_id')
        batch_op.drop_column('source_table')

    # ### end Alembic commands ###
