"""Add indexes to foreign key columns for performance

Revision ID: add_fk_indexes_20260907_205220
Revises:
Create Date: 2026-09-07 20:52:20

"""
from alembic import op
import sqlalchemy as sa

def safe_create_index(index_name, table_name, columns):
    try:
        conn = op.get_bind()
        inspector = sa.inspect(conn)
        if table_name in inspector.get_table_names():
            op.create_index(index_name, table_name, columns, unique=False)
            print(f'✅ Created index {index_name}')
        else:
            print(f'⚠️  Skipped {index_name}: table {table_name} does not exist yet')
    except Exception as e:
        print(f'⚠️  Error creating {index_name}: {e}')

def safe_drop_index(index_name, table_name):
    try:
        conn = op.get_bind()
        inspector = sa.inspect(conn)
        if table_name in inspector.get_table_names():
            op.drop_index(index_name, table_name=table_name)
            print(f'✅ Dropped index {index_name}')
        else:
            print(f'⚠️  Skipped dropping {index_name}: table {table_name} does not exist')
    except Exception as e:
        print(f'⚠️  Error dropping {index_name}: {e}')




# revision identifiers, used by Alembic.
revision = 'add_fk_indexes_20260907_205220'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    """Add indexes to all foreign key columns for query performance."""

    safe_create_index("ix_nursing_note_nurse_id", "nursing_note", ["nurse_id"])
    safe_create_index("ix_nursing_care_task_nurse_id", "nursing_care_task", ["nurse_id"])
    safe_create_index("ix_vitals_nurse_id", "vitals", ["nurse_id"])
    safe_create_index("ix_partogram_recorded_by", "partogram", ["recorded_by"])
    safe_create_index("ix_medication_admin_recorded_by", "medication_admin", ["recorded_by"])
    safe_create_index("ix_messages_sender_id", "messages", ["sender_id"])
    safe_create_index("ix_messages_receiver_id", "messages", ["receiver_id"])
    safe_create_index("ix_notifications_receiver_id", "notifications", ["receiver_id"])
    safe_create_index("ix_triage_assessment_nurse_id", "triage_assessment", ["nurse_id"])
    safe_create_index("ix_triage_assessment_vitals_id", "triage_assessment", ["vitals_id"])
    safe_create_index("ix_prescribed_medicine_patient_id", "prescribed_medicine", ["patient_id"])
    safe_create_index("ix_prescribed_medicine_medicine_id", "prescribed_medicine", ["medicine_id"])
    safe_create_index("ix_requested_lab_lab_test_id", "requested_lab", ["lab_test_id"])
    safe_create_index("ix_requested_image_patient_id", "requested_image", ["patient_id"])
    safe_create_index("ix_requested_image_imaging_id", "requested_image", ["imaging_id"])
    safe_create_index("ix_requested_image_result_id", "requested_image", ["result_id"])
    safe_create_index("ix_theatre_list_procedure_id", "theatre_list", ["procedure_id"])
    safe_create_index("ix_admitted_patient_ward_id", "admitted_patient", ["ward_id"])
    safe_create_index("ix_ward_bed_history_ward_id", "ward_bed_history", ["ward_id"])
    safe_create_index("ix_ward_room_ward_id", "ward_room", ["ward_id"])
    safe_create_index("ix_bed_room_id", "bed", ["room_id"])
    safe_create_index("ix_ward_round_admission_id", "ward_round", ["admission_id"])
    safe_create_index("ix_ward_round_doctor_id", "ward_round", ["doctor_id"])
    safe_create_index("ix_disease_keyword_disease_id", "disease_keyword", ["disease_id"])
    safe_create_index("ix_disease_management_plan_disease_id", "disease_management_plan", ["disease_id"])
    safe_create_index("ix_disease_symptom_disease_id", "disease_symptom", ["disease_id"])
    safe_create_index("ix_disease_symptom_symptom_id", "disease_symptom", ["symptom_id"])
    safe_create_index("ix_disease_lab_disease_id", "disease_lab", ["disease_id"])
    safe_create_index("ix_oncology_drug_category_id", "oncology_drug", ["category_id"])
    safe_create_index("ix_oncology_regimen_category_id", "oncology_regimen", ["category_id"])
    safe_create_index("ix_regimen_drug_association_regimen_id", "regimen_drug_association", ["regimen_id"])
    safe_create_index("ix_regimen_drug_association_drug_id", "regimen_drug_association", ["drug_id"])
    safe_create_index("ix_special_warning_drug_id", "special_warning", ["drug_id"])
    safe_create_index("ix_oncology_booking_patient_id", "oncology_booking", ["patient_id"])
    safe_create_index("ix_prescription_drug_detail_prescription_id", "prescription_drug_detail", ["prescription_id"])
    safe_create_index("ix_prescription_drug_detail_drug_id", "prescription_drug_detail", ["drug_id"])
    safe_create_index("ix_cancer_type_stage_cancer_type_id", "cancer_type_stage", ["cancer_type_id"])
    safe_create_index("ix_cancer_type_stage_cancer_stage_id", "cancer_type_stage", ["cancer_stage_id"])
    safe_create_index("ix_cancer_detail_cancer_type_id", "cancer_detail", ["cancer_type_id"])
    safe_create_index("ix_log_user_id", "log", ["user_id"])
    safe_create_index("ix_purchase_order_created_by_id", "purchase_order", ["created_by_id"])
    safe_create_index("ix_purchase_order_approved_by_id", "purchase_order", ["approved_by_id"])
    safe_create_index("ix_purchase_order_received_by_id", "purchase_order", ["received_by_id"])
    safe_create_index("ix_supplier_return_created_by_id", "supplier_return", ["created_by_id"])
    safe_create_index("ix_stock_disposal_created_by_id", "stock_disposal", ["created_by_id"])
    safe_create_index("ix_stock_disposal_approved_by_id", "stock_disposal", ["approved_by_id"])
    safe_create_index("ix_stock_disposal_item_batch_id", "stock_disposal_item", ["batch_id"])
    safe_create_index("ix_charge_category_id", "charge", ["category_id"])
    safe_create_index("ix_billing_charge_id", "billing", ["charge_id"])
    safe_create_index("ix_drugs_bill_drug_id", "drugs_bill", ["drug_id"])
    safe_create_index("ix_invoice_created_by", "invoice", ["created_by"])
    safe_create_index("ix_invoice_line_item_charge_id", "invoice_line_item", ["charge_id"])
    safe_create_index("ix_payment_recorded_by", "payment", ["recorded_by"])
    safe_create_index("ix_stock_take_created_by_id", "stock_take", ["created_by_id"])
    safe_create_index("ix_employee_updated_by", "employee", ["updated_by"])
    safe_create_index("ix_payroll_employee_id", "payroll", ["employee_id"])
    safe_create_index("ix_leave_employee_id", "leave", ["employee_id"])
    safe_create_index("ix_custom_rule_employee_id", "custom_rule", ["employee_id"])
    safe_create_index("ix_audit_log_user_id", "audit_log", ["user_id"])
    safe_create_index("ix_staff_credential_employee_id", "staff_credential", ["employee_id"])
    safe_create_index("ix_stock_movement_batch_id", "stock_movement", ["batch_id"])
    safe_create_index("ix_stock_movement_user_id", "stock_movement", ["user_id"])
    safe_create_index("ix_stock_movement_facility_id", "stock_movement", ["facility_id"])
    safe_create_index("ix_drug_category_id", "drug", ["category_id"])
    safe_create_index("ix_batch_drug_id", "batch", ["drug_id"])
    safe_create_index("ix_purchase_drug_id", "purchase", ["drug_id"])
    safe_create_index("ix_purchase_batch_id", "purchase", ["batch_id"])
    safe_create_index("ix_dispensed_drug_drug_id", "dispensed_drug", ["drug_id"])
    safe_create_index("ix_dispensed_drug_batch_id", "dispensed_drug", ["batch_id"])
    safe_create_index("ix_expiry_drug_id", "expiry", ["drug_id"])
    safe_create_index("ix_drug_request_requested_by", "drug_request", ["requested_by"])
    safe_create_index("ix_request_item_request_id", "request_item", ["request_id"])
    safe_create_index("ix_request_item_drug_id", "request_item", ["drug_id"])
    safe_create_index("ix_imaging_result_imaging_id", "imaging_result", ["imaging_id"])
    safe_create_index("ix_imaging_result_updated_by", "imaging_result", ["updated_by"])
    safe_create_index("ix_patient_created_by", "patient", ["created_by"])
    safe_create_index("ix_patient_updated_by", "patient", ["updated_by"])
    safe_create_index("ix_patient_merge_merged_by", "patient_merge", ["merged_by"])
    safe_create_index("ix_clinic_booking_clinic_id", "clinic_booking", ["clinic_id"])
    safe_create_index("ix_patient_allergy_recorded_by", "patient_allergy", ["recorded_by"])
    safe_create_index("ix_patient_problem_created_by", "patient_problem", ["created_by"])
    safe_create_index("ix_patient_user_patient_id", "patient_user", ["patient_id"])
    safe_create_index("ix_transfer_order_created_by_id", "transfer_order", ["created_by_id"])
    safe_create_index("ix_transfer_order_dispatched_by_id", "transfer_order", ["dispatched_by_id"])
    safe_create_index("ix_transfer_order_received_by_id", "transfer_order", ["received_by_id"])
    safe_create_index("ix_patient_insurance_verified_by", "patient_insurance", ["verified_by"])
    safe_create_index("ix_claim_patient_insurance_id", "claim", ["patient_insurance_id"])
    safe_create_index("ix_claim_created_by", "claim", ["created_by"])
    safe_create_index("ix_mortuary_data_recorded_by", "mortuary_data", ["recorded_by"])
    safe_create_index("ix_non_pharm_item_category_id", "non_pharm_item", ["category_id"])
    safe_create_index("ix_other_order_requested_by", "other_order", ["requested_by"])
    safe_create_index("ix_other_order_item_id", "other_order", ["item_id"])
    safe_create_index("ix_lab_result_template_test_id", "lab_result_template", ["test_id"])
    safe_create_index("ix_lab_result_lab_test_id", "lab_result", ["lab_test_id"])
    safe_create_index("ix_lab_result_updated_by", "lab_result", ["updated_by"])
    safe_create_index("ix_lab_result_verified_by", "lab_result", ["verified_by"])


def downgrade():
    """Remove indexes from foreign key columns."""

    safe_drop_index("ix_lab_result_verified_by", "lab_result")
    safe_drop_index("ix_lab_result_updated_by", "lab_result")
    safe_drop_index("ix_lab_result_lab_test_id", "lab_result")
    safe_drop_index("ix_lab_result_template_test_id", "lab_result_template")
    safe_drop_index("ix_other_order_item_id", "other_order")
    safe_drop_index("ix_other_order_requested_by", "other_order")
    safe_drop_index("ix_non_pharm_item_category_id", "non_pharm_item")
    safe_drop_index("ix_mortuary_data_recorded_by", "mortuary_data")
    safe_drop_index("ix_claim_created_by", "claim")
    safe_drop_index("ix_claim_patient_insurance_id", "claim")
    safe_drop_index("ix_patient_insurance_verified_by", "patient_insurance")
    safe_drop_index("ix_transfer_order_received_by_id", "transfer_order")
    safe_drop_index("ix_transfer_order_dispatched_by_id", "transfer_order")
    safe_drop_index("ix_transfer_order_created_by_id", "transfer_order")
    safe_drop_index("ix_patient_user_patient_id", "patient_user")
    safe_drop_index("ix_patient_problem_created_by", "patient_problem")
    safe_drop_index("ix_patient_allergy_recorded_by", "patient_allergy")
    safe_drop_index("ix_clinic_booking_clinic_id", "clinic_booking")
    safe_drop_index("ix_patient_merge_merged_by", "patient_merge")
    safe_drop_index("ix_patient_updated_by", "patient")
    safe_drop_index("ix_patient_created_by", "patient")
    safe_drop_index("ix_imaging_result_updated_by", "imaging_result")
    safe_drop_index("ix_imaging_result_imaging_id", "imaging_result")
    safe_drop_index("ix_request_item_drug_id", "request_item")
    safe_drop_index("ix_request_item_request_id", "request_item")
    safe_drop_index("ix_drug_request_requested_by", "drug_request")
    safe_drop_index("ix_expiry_drug_id", "expiry")
    safe_drop_index("ix_dispensed_drug_batch_id", "dispensed_drug")
    safe_drop_index("ix_dispensed_drug_drug_id", "dispensed_drug")
    safe_drop_index("ix_purchase_batch_id", "purchase")
    safe_drop_index("ix_purchase_drug_id", "purchase")
    safe_drop_index("ix_batch_drug_id", "batch")
    safe_drop_index("ix_drug_category_id", "drug")
    safe_drop_index("ix_stock_movement_facility_id", "stock_movement")
    safe_drop_index("ix_stock_movement_user_id", "stock_movement")
    safe_drop_index("ix_stock_movement_batch_id", "stock_movement")
    safe_drop_index("ix_staff_credential_employee_id", "staff_credential")
    safe_drop_index("ix_audit_log_user_id", "audit_log")
    safe_drop_index("ix_custom_rule_employee_id", "custom_rule")
    safe_drop_index("ix_leave_employee_id", "leave")
    safe_drop_index("ix_payroll_employee_id", "payroll")
    safe_drop_index("ix_employee_updated_by", "employee")
    safe_drop_index("ix_stock_take_created_by_id", "stock_take")
    safe_drop_index("ix_payment_recorded_by", "payment")
    safe_drop_index("ix_invoice_line_item_charge_id", "invoice_line_item")
    safe_drop_index("ix_invoice_created_by", "invoice")
    safe_drop_index("ix_drugs_bill_drug_id", "drugs_bill")
    safe_drop_index("ix_billing_charge_id", "billing")
    safe_drop_index("ix_charge_category_id", "charge")
    safe_drop_index("ix_stock_disposal_item_batch_id", "stock_disposal_item")
    safe_drop_index("ix_stock_disposal_approved_by_id", "stock_disposal")
    safe_drop_index("ix_stock_disposal_created_by_id", "stock_disposal")
    safe_drop_index("ix_supplier_return_created_by_id", "supplier_return")
    safe_drop_index("ix_purchase_order_received_by_id", "purchase_order")
    safe_drop_index("ix_purchase_order_approved_by_id", "purchase_order")
    safe_drop_index("ix_purchase_order_created_by_id", "purchase_order")
    safe_drop_index("ix_log_user_id", "log")
    safe_drop_index("ix_cancer_detail_cancer_type_id", "cancer_detail")
    safe_drop_index("ix_cancer_type_stage_cancer_stage_id", "cancer_type_stage")
    safe_drop_index("ix_cancer_type_stage_cancer_type_id", "cancer_type_stage")
    safe_drop_index("ix_prescription_drug_detail_drug_id", "prescription_drug_detail")
    safe_drop_index("ix_prescription_drug_detail_prescription_id", "prescription_drug_detail")
    safe_drop_index("ix_oncology_booking_patient_id", "oncology_booking")
    safe_drop_index("ix_special_warning_drug_id", "special_warning")
    safe_drop_index("ix_regimen_drug_association_drug_id", "regimen_drug_association")
    safe_drop_index("ix_regimen_drug_association_regimen_id", "regimen_drug_association")
    safe_drop_index("ix_oncology_regimen_category_id", "oncology_regimen")
    safe_drop_index("ix_oncology_drug_category_id", "oncology_drug")
    safe_drop_index("ix_disease_lab_disease_id", "disease_lab")
    safe_drop_index("ix_disease_symptom_symptom_id", "disease_symptom")
    safe_drop_index("ix_disease_symptom_disease_id", "disease_symptom")
    safe_drop_index("ix_disease_management_plan_disease_id", "disease_management_plan")
    safe_drop_index("ix_disease_keyword_disease_id", "disease_keyword")
    safe_drop_index("ix_ward_round_doctor_id", "ward_round")
    safe_drop_index("ix_ward_round_admission_id", "ward_round")
    safe_drop_index("ix_bed_room_id", "bed")
    safe_drop_index("ix_ward_room_ward_id", "ward_room")
    safe_drop_index("ix_ward_bed_history_ward_id", "ward_bed_history")
    safe_drop_index("ix_admitted_patient_ward_id", "admitted_patient")
    safe_drop_index("ix_theatre_list_procedure_id", "theatre_list")
    safe_drop_index("ix_requested_image_result_id", "requested_image")
    safe_drop_index("ix_requested_image_imaging_id", "requested_image")
    safe_drop_index("ix_requested_image_patient_id", "requested_image")
    safe_drop_index("ix_requested_lab_lab_test_id", "requested_lab")
    safe_drop_index("ix_prescribed_medicine_medicine_id", "prescribed_medicine")
    safe_drop_index("ix_prescribed_medicine_patient_id", "prescribed_medicine")
    safe_drop_index("ix_triage_assessment_vitals_id", "triage_assessment")
    safe_drop_index("ix_triage_assessment_nurse_id", "triage_assessment")
    safe_drop_index("ix_notifications_receiver_id", "notifications")
    safe_drop_index("ix_messages_receiver_id", "messages")
    safe_drop_index("ix_messages_sender_id", "messages")
    safe_drop_index("ix_medication_admin_recorded_by", "medication_admin")
    safe_drop_index("ix_partogram_recorded_by", "partogram")
    safe_drop_index("ix_vitals_nurse_id", "vitals")
    safe_drop_index("ix_nursing_care_task_nurse_id", "nursing_care_task")
    safe_drop_index("ix_nursing_note_nurse_id", "nursing_note")