"""add encounter_id to Invoice and InvoiceLineItem

Revision ID: c42a332c8f5f
Revises: 08d341f1843b
Create Date: 2026-09-08 23:28:55.964841

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c42a332c8f5f'
down_revision = '08d341f1843b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_line_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encounter_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_invoice_line_items_encounter_id'), ['encounter_id'], unique=False)
        batch_op.create_foreign_key(None, 'encounters', ['encounter_id'], ['id'])

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encounter_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_invoices_encounter_id'), ['encounter_id'], unique=False)
        batch_op.create_foreign_key(None, 'encounters', ['encounter_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_invoices_encounter_id'))
        batch_op.drop_column('encounter_id')

    with op.batch_alter_table('invoice_line_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_invoice_line_items_encounter_id'))
        batch_op.drop_column('encounter_id')

    # ### end Alembic commands ###
