"""gap8_lims_specimens_westgard_qc

Revision ID: d1326ffcbc3f
Revises: ee4c1ca9fcdc
Create Date: 2026-09-13 23:19:48.847341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1326ffcbc3f'
down_revision = 'ee4c1ca9fcdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_qc_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('control_name', sa.String(length=100), nullable=False),
    sa.Column('lot_number', sa.String(length=50), nullable=False),
    sa.Column('analyzer_name', sa.String(length=100), nullable=False),
    sa.Column('parameter_name', sa.String(length=100), nullable=False),
    sa.Column('target_mean', sa.Float(), nullable=False),
    sa.Column('target_sd', sa.Float(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lab_qc_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qc_sample_id', sa.Integer(), nullable=False),
    sa.Column('run_timestamp', sa.DateTime(), nullable=False),
    sa.Column('measured_value', sa.Float(), nullable=False),
    sa.Column('z_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('violated_rules', sa.Text(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['qc_sample_id'], ['lab_qc_samples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specimens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=50), nullable=False),
    sa.Column('requested_lab_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.String(length=20), nullable=False),
    sa.Column('specimen_type', sa.String(length=50), nullable=False),
    sa.Column('container_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('collected_by_id', sa.Integer(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=100), nullable=True),
    sa.Column('chain_of_custody', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collected_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.ForeignKeyConstraint(['requested_lab_id'], ['requested_labs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('specimens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_specimens_barcode'), ['barcode'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specimens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_specimens_barcode'))

    op.drop_table('specimens')
    op.drop_table('lab_qc_results')
    op.drop_table('lab_qc_samples')
    # ### end Alembic commands ###
