"""Add room_id to admitted_patients table

Revision ID: d20891842474
Revises: c42a332c8f5f
Create Date: 2026-09-10 12:49:26.185412

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd20891842474'
down_revision = 'c42a332c8f5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admitted_patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bed_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'ward_rooms', ['room_id'], ['id'])
        batch_op.create_foreign_key(None, 'beds', ['bed_id'], ['id'])

    with op.batch_alter_table('anc_visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encounter_id', sa.Integer(), nullable=True))
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_anc_visits_encounter_id'), ['encounter_id'], unique=False)
        batch_op.create_foreign_key(None, 'encounters', ['encounter_id'], ['id'])

    with op.batch_alter_table('encounters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_encounters_stage'), ['stage'], unique=False)

    with op.batch_alter_table('immunization_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encounter_id', sa.Integer(), nullable=True))
        batch_op.alter_column('child_patient_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_immunization_records_encounter_id'), ['encounter_id'], unique=False)
        batch_op.create_foreign_key(None, 'encounters', ['encounter_id'], ['id'])

    with op.batch_alter_table('patient_users', schema=None) as batch_op:
        batch_op.alter_column('locked_until',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('reset_token_expiry',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('last_login',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('prescribed_medicines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encounter_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_prescribed_medicines_encounter_id'), ['encounter_id'], unique=False)
        batch_op.create_foreign_key(None, 'encounters', ['encounter_id'], ['id'])

    with op.batch_alter_table('requested_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encounter_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_requested_images_encounter_id'), ['encounter_id'], unique=False)
        batch_op.create_foreign_key(None, 'encounters', ['encounter_id'], ['id'])

    with op.batch_alter_table('requested_labs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encounter_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_requested_labs_encounter_id'), ['encounter_id'], unique=False)
        batch_op.create_foreign_key(None, 'encounters', ['encounter_id'], ['id'])

    with op.batch_alter_table('telemedicine_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encounter_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_telemedicine_sessions_encounter_id'), ['encounter_id'], unique=False)
        batch_op.create_foreign_key(None, 'encounters', ['encounter_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telemedicine_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_telemedicine_sessions_encounter_id'))
        batch_op.drop_column('encounter_id')

    with op.batch_alter_table('requested_labs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_requested_labs_encounter_id'))
        batch_op.drop_column('encounter_id')

    with op.batch_alter_table('requested_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_requested_images_encounter_id'))
        batch_op.drop_column('encounter_id')

    with op.batch_alter_table('prescribed_medicines', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_prescribed_medicines_encounter_id'))
        batch_op.drop_column('encounter_id')

    with op.batch_alter_table('patient_users', schema=None) as batch_op:
        batch_op.alter_column('last_login',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('reset_token_expiry',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('locked_until',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('immunization_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_immunization_records_encounter_id'))
        batch_op.alter_column('child_patient_id',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('encounter_id')

    with op.batch_alter_table('encounters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_encounters_stage'))

    with op.batch_alter_table('anc_visits', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_anc_visits_encounter_id'))
        batch_op.alter_column('patient_id',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('encounter_id')

    with op.batch_alter_table('admitted_patients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('bed_id')
        batch_op.drop_column('room_id')

    # ### end Alembic commands ###
