"""phase1_add_terminology_models_and_columns

Revision ID: e47ef5938c09
Revises: 8aad67911cb6
Create Date: 2026-09-11 16:56:49.339617

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e47ef5938c09'
down_revision = '8aad67911cb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labtests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loinc_code', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_labtests_loinc_code'), ['loinc_code'], unique=False)

    with op.batch_alter_table('patient_problems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('snomed_code', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_patient_problems_snomed_code'), ['snomed_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_problems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_problems_snomed_code'))
        batch_op.drop_column('snomed_code')

    with op.batch_alter_table('labtests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_labtests_loinc_code'))
        batch_op.drop_column('loinc_code')

    # ### end Alembic commands ###
