"""gap6_mch_cold_chain_vaccine_batches

Revision ID: ee4c1ca9fcdc
Revises: 9542765b5e8e
Create Date: 2026-09-13 23:04:17.076035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee4c1ca9fcdc'
down_revision = '9542765b5e8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vaccine_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vaccine_name', sa.String(length=100), nullable=False),
    sa.Column('batch_number', sa.String(length=80), nullable=False),
    sa.Column('manufacturer', sa.String(length=150), nullable=True),
    sa.Column('supplied_by', sa.String(length=150), nullable=True),
    sa.Column('quantity_vials', sa.Integer(), nullable=False),
    sa.Column('doses_per_vial', sa.Integer(), nullable=False),
    sa.Column('quantity_remaining_vials', sa.Integer(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('storage_location', sa.String(length=100), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('vvm_stage', sa.Integer(), nullable=False),
    sa.Column('is_cold_chain_breach', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vaccine_name', 'batch_number', name='uq_vaccine_batch')
    )
    with op.batch_alter_table('vaccine_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vaccine_batches_expiry_date'), ['expiry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_vaccine_batches_storage_location'), ['storage_location'], unique=False)
        batch_op.create_index(batch_op.f('ix_vaccine_batches_vaccine_name'), ['vaccine_name'], unique=False)

    op.create_table('vaccine_temperature_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('storage_location', sa.String(length=100), nullable=False),
    sa.Column('temperature_celsius', sa.Float(), nullable=False),
    sa.Column('is_breach', sa.Boolean(), nullable=False),
    sa.Column('breach_type', sa.String(length=20), nullable=True),
    sa.Column('sensor_id', sa.String(length=80), nullable=True),
    sa.Column('logged_by', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vaccine_temperature_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vaccine_temperature_logs_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vaccine_temperature_logs_storage_location'), ['storage_location'], unique=False)

    op.create_table('anaesthetic_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('theatre_entry_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=20), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=True),
    sa.Column('anaesthetist_id', sa.Integer(), nullable=True),
    sa.Column('asa_status', sa.String(length=10), nullable=False),
    sa.Column('is_emergency', sa.Boolean(), nullable=False),
    sa.Column('mallampati_class', sa.String(length=10), nullable=True),
    sa.Column('airway_management', sa.String(length=100), nullable=True),
    sa.Column('ett_size', sa.String(length=20), nullable=True),
    sa.Column('technique', sa.String(length=100), nullable=False),
    sa.Column('agents_administered_json', sa.Text(), nullable=True),
    sa.Column('vitals_series_json', sa.Text(), nullable=True),
    sa.Column('estimated_blood_loss_ml', sa.Integer(), nullable=False),
    sa.Column('crystalloids_ml', sa.Integer(), nullable=False),
    sa.Column('colloids_ml', sa.Integer(), nullable=False),
    sa.Column('blood_products_ml', sa.Integer(), nullable=False),
    sa.Column('urine_output_ml', sa.Integer(), nullable=False),
    sa.Column('complications_notes', sa.Text(), nullable=True),
    sa.Column('anaesthesia_start_time', sa.DateTime(), nullable=True),
    sa.Column('anaesthesia_end_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['anaesthetist_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.ForeignKeyConstraint(['theatre_entry_id'], ['theatre_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anaesthetic_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anaesthetic_records_encounter_id'), ['encounter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anaesthetic_records_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anaesthetic_records_theatre_entry_id'), ['theatre_entry_id'], unique=False)

    op.create_table('post_op_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('theatre_entry_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=20), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=True),
    sa.Column('surgeon_id', sa.Integer(), nullable=True),
    sa.Column('assistant_surgeon', sa.String(length=100), nullable=True),
    sa.Column('scrub_nurse', sa.String(length=100), nullable=True),
    sa.Column('circulating_nurse', sa.String(length=100), nullable=True),
    sa.Column('preop_diagnosis', sa.String(length=255), nullable=False),
    sa.Column('postop_diagnosis', sa.String(length=255), nullable=False),
    sa.Column('procedure_performed', sa.Text(), nullable=False),
    sa.Column('surgical_findings', sa.Text(), nullable=False),
    sa.Column('specimens_taken', sa.Text(), nullable=True),
    sa.Column('implants_inserted', sa.Text(), nullable=True),
    sa.Column('drains_tubes_placed', sa.Text(), nullable=True),
    sa.Column('aldrete_activity', sa.Integer(), nullable=False),
    sa.Column('aldrete_respiration', sa.Integer(), nullable=False),
    sa.Column('aldrete_circulation', sa.Integer(), nullable=False),
    sa.Column('aldrete_consciousness', sa.Integer(), nullable=False),
    sa.Column('aldrete_spo2', sa.Integer(), nullable=False),
    sa.Column('postop_instructions', sa.Text(), nullable=True),
    sa.Column('discharge_to', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.ForeignKeyConstraint(['surgeon_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['theatre_entry_id'], ['theatre_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post_op_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_op_notes_encounter_id'), ['encounter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_op_notes_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_op_notes_theatre_entry_id'), ['theatre_entry_id'], unique=False)

    op.create_table('surgical_instrument_counts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('theatre_entry_id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=True),
    sa.Column('scrub_nurse_id', sa.Integer(), nullable=True),
    sa.Column('circulating_nurse_id', sa.Integer(), nullable=True),
    sa.Column('tray_name_or_barcode', sa.String(length=100), nullable=False),
    sa.Column('sponges_initial', sa.Integer(), nullable=False),
    sa.Column('sponges_added', sa.Integer(), nullable=False),
    sa.Column('sponges_closing_cavity', sa.Integer(), nullable=False),
    sa.Column('sponges_closing_skin', sa.Integer(), nullable=False),
    sa.Column('needles_initial', sa.Integer(), nullable=False),
    sa.Column('needles_added', sa.Integer(), nullable=False),
    sa.Column('needles_closing_cavity', sa.Integer(), nullable=False),
    sa.Column('needles_closing_skin', sa.Integer(), nullable=False),
    sa.Column('instruments_initial', sa.Integer(), nullable=False),
    sa.Column('instruments_added', sa.Integer(), nullable=False),
    sa.Column('instruments_closing_cavity', sa.Integer(), nullable=False),
    sa.Column('instruments_closing_skin', sa.Integer(), nullable=False),
    sa.Column('count_reconciled', sa.Boolean(), nullable=False),
    sa.Column('xray_ordered_for_discrepancy', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['circulating_nurse_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['scrub_nurse_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['theatre_entry_id'], ['theatre_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('surgical_instrument_counts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_surgical_instrument_counts_encounter_id'), ['encounter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_surgical_instrument_counts_theatre_entry_id'), ['theatre_entry_id'], unique=False)

    op.create_table('who_surgical_checklists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('theatre_entry_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=20), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=True),
    sa.Column('sign_in_completed', sa.Boolean(), nullable=False),
    sa.Column('patient_identity_confirmed', sa.Boolean(), nullable=True),
    sa.Column('site_marked', sa.Boolean(), nullable=True),
    sa.Column('anaesthesia_safety_check_completed', sa.Boolean(), nullable=True),
    sa.Column('pulse_oximeter_functioning', sa.Boolean(), nullable=True),
    sa.Column('known_allergy', sa.Boolean(), nullable=True),
    sa.Column('allergy_details', sa.String(length=255), nullable=True),
    sa.Column('difficult_airway_risk', sa.Boolean(), nullable=True),
    sa.Column('airway_equipment_available', sa.Boolean(), nullable=True),
    sa.Column('blood_loss_risk_over_500ml', sa.Boolean(), nullable=True),
    sa.Column('iv_access_and_fluids_planned', sa.Boolean(), nullable=True),
    sa.Column('sign_in_completed_by', sa.Integer(), nullable=True),
    sa.Column('sign_in_completed_at', sa.DateTime(), nullable=True),
    sa.Column('time_out_completed', sa.Boolean(), nullable=False),
    sa.Column('team_members_introduced', sa.Boolean(), nullable=True),
    sa.Column('verbal_confirm_patient_site_procedure', sa.Boolean(), nullable=True),
    sa.Column('critical_steps_surgeon_reviewed', sa.Boolean(), nullable=True),
    sa.Column('critical_steps_anaesthetist_reviewed', sa.Boolean(), nullable=True),
    sa.Column('critical_steps_nursing_reviewed', sa.Boolean(), nullable=True),
    sa.Column('antibiotic_prophylaxis_given', sa.Boolean(), nullable=True),
    sa.Column('antibiotic_given_within_60min', sa.Boolean(), nullable=True),
    sa.Column('essential_imaging_displayed', sa.Boolean(), nullable=True),
    sa.Column('time_out_completed_by', sa.Integer(), nullable=True),
    sa.Column('time_out_completed_at', sa.DateTime(), nullable=True),
    sa.Column('sign_out_completed', sa.Boolean(), nullable=False),
    sa.Column('procedure_name_recorded', sa.String(length=255), nullable=True),
    sa.Column('instrument_sponge_needle_counts_correct', sa.Boolean(), nullable=True),
    sa.Column('specimens_labelled', sa.Boolean(), nullable=True),
    sa.Column('equipment_problems_addressed', sa.Boolean(), nullable=True),
    sa.Column('key_recovery_concerns_reviewed', sa.Text(), nullable=True),
    sa.Column('sign_out_completed_by', sa.Integer(), nullable=True),
    sa.Column('sign_out_completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.ForeignKeyConstraint(['sign_in_completed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sign_out_completed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['theatre_entry_id'], ['theatre_list.id'], ),
    sa.ForeignKeyConstraint(['time_out_completed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('who_surgical_checklists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_who_surgical_checklists_encounter_id'), ['encounter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_who_surgical_checklists_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_who_surgical_checklists_theatre_entry_id'), ['theatre_entry_id'], unique=False)

    with op.batch_alter_table('anc_visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blood_pressure_systolic', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('blood_pressure_diastolic', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('weight_kg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fundal_height_cm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('foetal_heart_rate', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('haemoglobin_g_dl', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('urine_protein', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('hiv_status', sa.String(length=20), nullable=True))

    with op.batch_alter_table('daily_kpi_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avg_length_of_stay', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bed_occupancy_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('thirty_day_readmission_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mortality_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('top_diagnoses_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('disease_surveillance_json', sa.JSON(), nullable=True))

    with op.batch_alter_table('imaging_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orthanc_uid', sa.String(length=100), nullable=True))
        # server_default='LOCAL' handles existing rows with no storage_backend set
        batch_op.add_column(sa.Column(
            'storage_backend', sa.String(length=50),
            nullable=False, server_default='LOCAL',
        ))
        batch_op.create_index(batch_op.f('ix_imaging_results_orthanc_uid'), ['orthanc_uid'], unique=False)

    with op.batch_alter_table('immunization_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_of_injection', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('administered_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('adverse_event_noted', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('vaccine_batch_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_immunization_records_vaccine_batch_id'), ['vaccine_batch_id'], unique=False)
        batch_op.create_foreign_key(None, 'vaccine_batches', ['vaccine_batch_id'], ['id'])

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('previous_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('entry_hash', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_logs_entry_hash'), ['entry_hash'], unique=False)

    with op.batch_alter_table('medication_admin', schema=None) as batch_op:
        # server_default=False handles existing rows
        batch_op.add_column(sa.Column('scan_verified', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('barcode_patient_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('barcode_drug_code', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('prescribed_medicine_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('override_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('override_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'prescribed_medicines', ['prescribed_medicine_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['override_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication_admin', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('override_by')
        batch_op.drop_column('override_reason')
        batch_op.drop_column('prescribed_medicine_id')
        batch_op.drop_column('barcode_drug_code')
        batch_op.drop_column('barcode_patient_id')
        batch_op.drop_column('scan_verified')

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logs_entry_hash'))
        batch_op.drop_column('entry_hash')
        batch_op.drop_column('previous_hash')

    with op.batch_alter_table('immunization_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_immunization_records_vaccine_batch_id'))
        batch_op.drop_column('vaccine_batch_id')
        batch_op.drop_column('adverse_event_noted')
        batch_op.drop_column('administered_by')
        batch_op.drop_column('site_of_injection')

    with op.batch_alter_table('imaging_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_imaging_results_orthanc_uid'))
        batch_op.drop_column('storage_backend')
        batch_op.drop_column('orthanc_uid')

    with op.batch_alter_table('daily_kpi_snapshots', schema=None) as batch_op:
        batch_op.drop_column('disease_surveillance_json')
        batch_op.drop_column('top_diagnoses_json')
        batch_op.drop_column('mortality_count')
        batch_op.drop_column('thirty_day_readmission_count')
        batch_op.drop_column('bed_occupancy_rate')
        batch_op.drop_column('avg_length_of_stay')

    with op.batch_alter_table('anc_visits', schema=None) as batch_op:
        batch_op.drop_column('hiv_status')
        batch_op.drop_column('urine_protein')
        batch_op.drop_column('haemoglobin_g_dl')
        batch_op.drop_column('foetal_heart_rate')
        batch_op.drop_column('fundal_height_cm')
        batch_op.drop_column('weight_kg')
        batch_op.drop_column('blood_pressure_diastolic')
        batch_op.drop_column('blood_pressure_systolic')

    with op.batch_alter_table('who_surgical_checklists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_who_surgical_checklists_theatre_entry_id'))
        batch_op.drop_index(batch_op.f('ix_who_surgical_checklists_patient_id'))
        batch_op.drop_index(batch_op.f('ix_who_surgical_checklists_encounter_id'))

    op.drop_table('who_surgical_checklists')
    with op.batch_alter_table('surgical_instrument_counts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_surgical_instrument_counts_theatre_entry_id'))
        batch_op.drop_index(batch_op.f('ix_surgical_instrument_counts_encounter_id'))

    op.drop_table('surgical_instrument_counts')
    with op.batch_alter_table('post_op_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_op_notes_theatre_entry_id'))
        batch_op.drop_index(batch_op.f('ix_post_op_notes_patient_id'))
        batch_op.drop_index(batch_op.f('ix_post_op_notes_encounter_id'))

    op.drop_table('post_op_notes')
    with op.batch_alter_table('anaesthetic_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anaesthetic_records_theatre_entry_id'))
        batch_op.drop_index(batch_op.f('ix_anaesthetic_records_patient_id'))
        batch_op.drop_index(batch_op.f('ix_anaesthetic_records_encounter_id'))

    op.drop_table('anaesthetic_records')
    with op.batch_alter_table('vaccine_temperature_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vaccine_temperature_logs_storage_location'))
        batch_op.drop_index(batch_op.f('ix_vaccine_temperature_logs_recorded_at'))

    op.drop_table('vaccine_temperature_logs')
    with op.batch_alter_table('vaccine_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vaccine_batches_vaccine_name'))
        batch_op.drop_index(batch_op.f('ix_vaccine_batches_storage_location'))
        batch_op.drop_index(batch_op.f('ix_vaccine_batches_expiry_date'))

    op.drop_table('vaccine_batches')
    # ### end Alembic commands ###
