"""add_weight_kg_and_voided_fields

Revision ID: f24bf71a06cb
Revises: d29e6b4f1a73
Create Date: 2026-09-17 13:58:27.898700

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f24bf71a06cb'
down_revision = 'd29e6b4f1a73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))

    with op.batch_alter_table('claim_submissions', schema=None) as batch_op:
        batch_op.alter_column('scrubbing_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'UNSCRUBBED'::character varying"))
        batch_op.alter_column('denial_risk_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))

    with op.batch_alter_table('dispensed_drugs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voided_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('voided_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('void_reason', sa.String(length=500), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['voided_by'], ['id'])

    with op.batch_alter_table('malaria_cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight_kg', sa.Float(), nullable=True))

    with op.batch_alter_table('non_pharm_items', schema=None) as batch_op:
        batch_op.alter_column('unit_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('post_op_notes', schema=None) as batch_op:
        batch_op.drop_column('total_aldrete_score')
        batch_op.drop_column('pacu_discharged_at')
        batch_op.drop_column('pacu_discharge_eligible')
        batch_op.drop_column('specimens_taken_details')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_op_notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specimens_taken_details', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pacu_discharge_eligible', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pacu_discharged_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_aldrete_score', sa.INTEGER(), server_default=sa.text('10'), autoincrement=False, nullable=True))

    with op.batch_alter_table('non_pharm_items', schema=None) as batch_op:
        batch_op.alter_column('unit_cost',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    with op.batch_alter_table('malaria_cases', schema=None) as batch_op:
        batch_op.drop_column('weight_kg')

    with op.batch_alter_table('dispensed_drugs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('void_reason')
        batch_op.drop_column('voided_at')
        batch_op.drop_column('voided_by')

    with op.batch_alter_table('claim_submissions', schema=None) as batch_op:
        batch_op.alter_column('denial_risk_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
        batch_op.alter_column('scrubbing_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'UNSCRUBBED'::character varying"))

    with op.batch_alter_table('beds', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
