"""add_moh731_and_moh729b_tables

Revision ID: f2a1cd436c77
Revises: f24bf71a06cb
Create Date: 2026-09-17 16:38:53.835997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2a1cd436c77'
down_revision = 'f24bf71a06cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moh_729b_arv_fcdrr_monthly',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('facility_id', sa.String(length=50), nullable=False),
    sa.Column('period', sa.String(length=6), nullable=False),
    sa.Column('arv_drug_code', sa.String(length=40), nullable=False),
    sa.Column('unit_pack_size', sa.String(length=20), nullable=False),
    sa.Column('patients_on_regimen', sa.Integer(), nullable=False),
    sa.Column('beginning_balance', sa.Integer(), nullable=False),
    sa.Column('quantity_received', sa.Integer(), nullable=False),
    sa.Column('quantity_dispensed', sa.Integer(), nullable=False),
    sa.Column('losses_adjustments', sa.Integer(), nullable=False),
    sa.Column('ending_balance', sa.Integer(), nullable=False),
    sa.Column('days_stocked_out', sa.Integer(), nullable=False),
    sa.Column('months_of_stock', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('quantity_requested', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('moh_729b_arv_fcdrr_monthly', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_moh_729b_arv_fcdrr_monthly_arv_drug_code'), ['arv_drug_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_moh_729b_arv_fcdrr_monthly_period'), ['period'], unique=False)

    op.create_table('moh_731_arv_regimen_patients_monthly',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('facility_id', sa.String(length=50), nullable=False),
    sa.Column('period', sa.String(length=6), nullable=False),
    sa.Column('regimen_code', sa.String(length=20), nullable=False),
    sa.Column('regimen_line', sa.String(length=20), nullable=False),
    sa.Column('active_patients_male', sa.Integer(), nullable=False),
    sa.Column('active_patients_female', sa.Integer(), nullable=False),
    sa.Column('total_active_patients', sa.Integer(), nullable=False),
    sa.Column('new_patients_started', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('moh_731_arv_regimen_patients_monthly', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_moh_731_arv_regimen_patients_monthly_period'), ['period'], unique=False)
        batch_op.create_index(batch_op.f('ix_moh_731_arv_regimen_patients_monthly_regimen_code'), ['regimen_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moh_731_arv_regimen_patients_monthly', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_moh_731_arv_regimen_patients_monthly_regimen_code'))
        batch_op.drop_index(batch_op.f('ix_moh_731_arv_regimen_patients_monthly_period'))

    op.drop_table('moh_731_arv_regimen_patients_monthly')
    with op.batch_alter_table('moh_729b_arv_fcdrr_monthly', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_moh_729b_arv_fcdrr_monthly_period'))
        batch_op.drop_index(batch_op.f('ix_moh_729b_arv_fcdrr_monthly_arv_drug_code'))

    op.drop_table('moh_729b_arv_fcdrr_monthly')
    # ### end Alembic commands ###
