"""add employee annual_leave_days

Revision ID: f9c69a8e3e2e
Revises: fefcbf381ba9
Create Date: 2026-09-18 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9c69a8e3e2e'
down_revision = 'fefcbf381ba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'annual_leave_days',
                sa.Integer(),
                nullable=False,
                server_default='21',
            )
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('annual_leave_days')
    # ### end Alembic commands ###
