"""add supply chain gaps storage condition rtv and disposals

Revision ID: fc41aabfed4a
Revises: 3059ae209032
Create Date: 2026-09-06 18:50:15.773460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc41aabfed4a'
down_revision = '3059ae209032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_disposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disposal_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('total_loss_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disposed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_disposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_disposals_disposal_number'), ['disposal_number'], unique=True)

    op.create_table('supplier_returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rtv_number', sa.String(length=50), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('total_credit_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_returns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_returns_po_id'), ['po_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_returns_rtv_number'), ['rtv_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_supplier_returns_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('stock_disposal_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disposal_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('drug_id', sa.Integer(), nullable=True),
    sa.Column('non_pharm_item_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('quantity_disposed', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['disposal_id'], ['stock_disposals.id'], ),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.ForeignKeyConstraint(['non_pharm_item_id'], ['non_pharm_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_disposal_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_disposal_items_disposal_id'), ['disposal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_disposal_items_drug_id'), ['drug_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_disposal_items_non_pharm_item_id'), ['non_pharm_item_id'], unique=False)

    op.create_table('supplier_return_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_return_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('drug_id', sa.Integer(), nullable=True),
    sa.Column('non_pharm_item_id', sa.Integer(), nullable=True),
    sa.Column('batch_number', sa.String(length=50), nullable=True),
    sa.Column('quantity_returned', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.ForeignKeyConstraint(['non_pharm_item_id'], ['non_pharm_items.id'], ),
    sa.ForeignKeyConstraint(['supplier_return_id'], ['supplier_returns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_return_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_return_items_drug_id'), ['drug_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_return_items_non_pharm_item_id'), ['non_pharm_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_return_items_supplier_return_id'), ['supplier_return_id'], unique=False)

    with op.batch_alter_table('drugs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_condition', sa.String(length=50), nullable=False, server_default='ROOM_TEMP'))

    with op.batch_alter_table('non_pharm_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_condition', sa.String(length=50), nullable=False, server_default='ROOM_TEMP'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('non_pharm_items', schema=None) as batch_op:
        batch_op.drop_column('storage_condition')

    with op.batch_alter_table('drugs', schema=None) as batch_op:
        batch_op.drop_column('storage_condition')

    with op.batch_alter_table('supplier_return_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_return_items_supplier_return_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_return_items_non_pharm_item_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_return_items_drug_id'))

    op.drop_table('supplier_return_items')
    with op.batch_alter_table('stock_disposal_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_disposal_items_non_pharm_item_id'))
        batch_op.drop_index(batch_op.f('ix_stock_disposal_items_drug_id'))
        batch_op.drop_index(batch_op.f('ix_stock_disposal_items_disposal_id'))

    op.drop_table('stock_disposal_items')
    with op.batch_alter_table('supplier_returns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_returns_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_returns_rtv_number'))
        batch_op.drop_index(batch_op.f('ix_supplier_returns_po_id'))

    op.drop_table('supplier_returns')
    with op.batch_alter_table('stock_disposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_disposals_disposal_number'))

    op.drop_table('stock_disposals')
    # ### end Alembic commands ###
