"""add PMTCT and GeneXpert fields

Revision ID: fefcbf381ba9
Revises: 315d18d94f09
Create Date: 2026-09-17 17:59:28.551401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fefcbf381ba9'
down_revision = '315d18d94f09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('art_enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pregnant', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_breastfeeding', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('hei_infant_prophylaxis', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('eid_dna_pcr_6wk_result', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('eid_dna_pcr_12mo_result', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('eid_antibody_18mo_result', sa.String(length=20), nullable=True))

    with op.batch_alter_table('sputum_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genexpert_mtb_result', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('rifampicin_resistance', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('fluoroquinolone_resistance', sa.String(length=30), nullable=True))

    with op.batch_alter_table('tb_enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recommended_regimen_code', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_enrollments', schema=None) as batch_op:
        batch_op.drop_column('recommended_regimen_code')

    with op.batch_alter_table('sputum_results', schema=None) as batch_op:
        batch_op.drop_column('fluoroquinolone_resistance')
        batch_op.drop_column('rifampicin_resistance')
        batch_op.drop_column('genexpert_mtb_result')

    with op.batch_alter_table('art_enrollments', schema=None) as batch_op:
        batch_op.drop_column('eid_antibody_18mo_result')
        batch_op.drop_column('eid_dna_pcr_12mo_result')
        batch_op.drop_column('eid_dna_pcr_6wk_result')
        batch_op.drop_column('hei_infant_prophylaxis')
        batch_op.drop_column('is_breastfeeding')
        batch_op.drop_column('is_pregnant')

    # ### end Alembic commands ###
