PRIORITY_SYMPTOMS = [
    "chest pain",
    "shortness of breath",
    "severe headache",
    "loss of consciousness",
    "sudden weakness on one side",
    "slurred speech",
    "acute abdominal pain",
    "persistent vomiting",
    "high fever with confusion",
    "seizures",
    "uncontrolled bleeding",
    "trauma or head injury",
    "severe allergic reaction",
    "burns involving face or genitals",
    "suicidal thoughts",
    "sudden vision loss",
    "difficulty breathing",
    "palpitations",
    "new onset confusion",
    "stiff neck with fever",
    "bloody stools",
    "hematuria (blood in urine)",
    "inability to pass urine",
    "severe back pain",
    "persistent chest tightness",
    "cyanosis (bluish lips or fingertips)",
    "pregnancy with bleeding or pain",
    "reduced fetal movement",
    "paralysis",
    "sudden severe dizziness",
    "altered mental status",
    "extreme fatigue with fever",
    "non-blanching rash",
    "persistent high fever (> 39.5°C)",
    "rigors or chills with fever",
    "suspected meningitis",
    "intractable hiccups or vomiting",
    "postpartum hemorrhage",
    "new onset seizure",
    "massive hemoptysis",
    "difficulty speaking",
    "painful or swollen leg with redness",
    "unresponsive to verbal or painful stimuli",
    "bradycardia with symptoms",
    "tachycardia >130 bpm",
    "hypotension with symptoms",
    "sudden chest pressure or squeezing",
    "anaphylaxis",
    "exposure to toxin or poison",
    "near-drowning or asphyxiation event",
    "violent behavior or psychosis",
    "sudden onset of severe joint pain",
    "pale, clammy skin with dizziness",
    "foreign body in airway",
    "stridor",
    "history of recent fall with anticoagulation",
    "pain out of proportion to exam",
    "sudden inability to walk"
]
