PRIORITY_SYMPTOMS = [
    "chest pain",
    "shortness of breath",
    "severe headache",
    "loss of consciousness",
    "sudden weakness on one side",
    "slurred speech",
    "acute abdominal pain",
    "persistent vomiting",
    "high fever with confusion",
    "seizures",
    "uncontrolled bleeding",
    "trauma or head injury",
    "severe allergic reaction",
    "burns involving face or genitals",
    "suicidal thoughts",
    "sudden vision loss",
    "difficulty breathing",
    "palpitations",
    "new onset confusion",
    "stiff neck with fever",
    "bloody stools",
    "hematuria (blood in urine)",
    "inability to pass urine",
    "severe back pain",
    "persistent chest tightness",
    "cyanosis (bluish lips or fingertips)",
    "pregnancy with bleeding or pain",
    "reduced fetal movement",
    "paralysis",
    "sudden severe dizziness"
]
