texts = [
    "Patient has a breast mass with axillary lymphadenopathy and peau d'orange appearance.",
    "Mammography revealed spiculated mass in the upper outer quadrant of the left breast.",
    "Biopsy of breast tissue confirmed invasive ductal carcinoma, ER/PR positive.",
    "Colonoscopy identified a bleeding polypoidal lesion in the sigmoid colon; biopsy showed adenocarcinoma.",
    "Patient complains of altered bowel habits and unintentional weight loss; CEA levels elevated.",
    "CT abdomen shows thickened colonic wall in the transverse colon with adjacent lymphadenopathy.",
    "Elevated PSA levels and firm nodular prostate on DRE; TRUS-guided biopsy confirms adenocarcinoma.",
    "MRI pelvis reveals extracapsular extension of prostate cancer; Gleason score 4+5.",
    "CT scan shows a 3.5 cm spiculated mass in the upper lobe of the right lung with mediastinal lymphadenopathy.",
    "Patient presents with hemoptysis and chronic cough; chest X-ray shows suspicious opacity.",
    "PET-CT confirms FDG-avid lesion in the right hilum suggestive of lung cancer.",
    "Ovarian mass detected on ultrasound with ascites and omental caking.",
    "CA-125 significantly elevated in a postmenopausal woman; CT shows bilateral adnexal masses.",
    "Laparoscopy reveals solid ovarian tumor with peritoneal metastases; biopsy confirms serous cystadenocarcinoma.",
    "Patient has a family history of breast and ovarian cancer; BRCA1 mutation positive.",
    "Patient reports difficulty urinating and pelvic discomfort; PSA is 65 ng/mL.",
    "Colonoscopy shows ulcerated mass in the rectosigmoid region with high-grade dysplasia.",
    "Chest CT shows solitary pulmonary nodule with irregular borders in a chronic smoker.",
    "Breast MRI shows multifocal lesions in the right breast with lymph node involvement.",
    "Endoscopic biopsy of colonic lesion reveals mucinous adenocarcinoma; patient has anemia and fatigue.",
    "Young woman with abdominal bloating and early satiety found to have complex adnexal mass on imaging.",
    "Digital rectal exam shows induration of prostate; MRI suggests seminal vesicle invasion.",
    "Biopsy confirms triple-negative breast cancer; staging workup underway.",
    "Lung lesion biopsy reveals non-small cell carcinoma; EGFR mutation testing pending.",
    "Follow-up colonoscopy in a high-risk patient shows sessile polyp with high-grade dysplasia.",
    "Postmenopausal bleeding prompts imaging; ultrasound shows complex ovarian cyst with solid areas.",
    "Histopathology of excised breast lump reveals HER2-positive ductal carcinoma in situ.",
    "Prostate biopsy shows poorly differentiated carcinoma with perineural invasion.",
    "PET scan shows increased uptake in left ovarian region; CA-125 and HE4 elevated.",
    "Left-sided chest pain and dyspnea; pleural fluid cytology positive for malignant cells (lung origin).",
    "Patient with Lynch syndrome presents with right colon mass; biopsy confirms adenocarcinoma.",
    "Young male with elevated PSA due to prostatitis ruled out; biopsy confirms early-stage carcinoma.",
    "CT-guided needle biopsy of lung lesion shows squamous cell carcinoma.",
    "Mass in left lower quadrant noted during routine colon screening; family history of colon cancer.",
    "Abdominal ultrasound shows large hypoechoic ovarian mass with irregular margins and internal septations.",
    "Breast lump rapidly increasing in size; biopsy shows inflammatory breast cancer.",
    "Patient complains of fatigue, abdominal pain, and melena; colonoscopy finds tumor at hepatic flexure.",
    "Older male with LUTS and elevated PSA referred for biopsy; MRI shows PI-RADS 5 lesion.",
    "Suspicious calcifications seen on mammogram; biopsy reveals lobular carcinoma in situ.",
    "Patient with persistent cough and weight loss; CT thorax reveals a 4 cm mass in the left lung with hilar lymphadenopathy.",
    "Core biopsy of breast mass shows medullary carcinoma; patient reports nipple discharge.",
    "Colonoscopy reveals multiple polyps in the ascending colon; histopathology confirms tubular adenoma with low-grade dysplasia.",
    "Elevated CA-19-9 and jaundice; ERCP shows a pancreatic head mass suggestive of pancreatic adenocarcinoma.",
    "MRI of the pelvis identifies a large uterine mass with myometrial invasion; biopsy confirms endometrial carcinoma.",
    "Patient presents with bone pain and hypercalcemia; bone scan shows lytic lesions suggestive of metastatic breast cancer.",
    "Chest X-ray reveals a coin lesion in the right lower lobe; bronchoscopy confirms small cell lung cancer.",
    "Young female with irregular menses and pelvic pain; ultrasound shows a 6 cm ovarian cyst with solid components.",
    "Prostate MRI reveals a PI-RADS 4 lesion in the peripheral zone; biopsy confirms Gleason 3+4 adenocarcinoma.",
    "Patient with a history of smoking presents with hoarseness; laryngoscopy reveals squamous cell carcinoma of the vocal cord.",
    "CT abdomen shows a 5 cm renal mass with irregular enhancement; biopsy confirms renal cell carcinoma.",
    "Elevated AFP and a liver mass on ultrasound in a patient with hepatitis B; MRI suggests hepatocellular carcinoma.",
    "Breast ultrasound shows a hypoechoic mass with irregular margins; biopsy confirms invasive lobular carcinoma.",
    "Patient with rectal bleeding and tenesmus; sigmoidoscopy reveals a circumferential mass with adenocarcinoma on biopsy.",
    "PET-CT shows hypermetabolic lymph nodes in the retroperitoneum; biopsy suggests lymphoma.",
    "Older female with vaginal bleeding; endometrial biopsy confirms high-grade endometrioid adenocarcinoma.",
    "CT thorax identifies a pleural-based mass; biopsy reveals malignant mesothelioma in an asbestos-exposed patient.",
    "Patient with a palpable neck mass; ultrasound-guided FNA confirms papillary thyroid carcinoma.",
    "Colonoscopy in a patient with a family history of FAP reveals hundreds of polyps; biopsy shows adenomas with high-grade dysplasia.",
    "MRI brain shows a ring-enhancing lesion; stereotactic biopsy confirms glioblastoma multiforme.",
    "Patient with epigastric pain and weight loss; CT shows a pancreatic tail mass with liver metastases.",
    "Breast mammogram reveals architectural distortion; biopsy confirms invasive ductal carcinoma, HER2-negative.",
    "Elevated PSA and a hard prostate on DRE; biopsy reveals Gleason 4+4 adenocarcinoma with bone metastases on scan.",
    "Young male with testicular swelling; ultrasound shows a hypoechoic mass, and tumor markers (AFP, hCG) are elevated.",
    "CT chest shows ground-glass opacities and a central mass; biopsy confirms adenocarcinoma of the lung.",
    "Patient with abdominal distension; CT reveals a large gastric mass; biopsy confirms diffuse-type gastric adenocarcinoma.",
    "MRI pelvis shows a cervical mass with parametrial invasion; biopsy confirms squamous cell carcinoma of the cervix.",
    "Patient with night sweats and lymphadenopathy; excisional biopsy of cervical node confirms Hodgkin lymphoma.",
    "Ultrasound reveals a complex ovarian mass in a young female; laparoscopy confirms endometrioid ovarian carcinoma.",
    "Chest CT shows a 2 cm nodule in the left upper lobe; biopsy reveals carcinoid tumor.",
    "Patient with a history of ulcerative colitis; colonoscopy shows a flat lesion with high-grade dysplasia.",
    "MRI of the spine shows vertebral metastases; primary lung cancer confirmed via bronchoscopy.",
    "Elevated CA-15-3 in a patient with a breast lump; biopsy confirms mucinous carcinoma of the breast.",
    "Patient with hematuria and flank pain; CT urogram shows a bladder mass; biopsy confirms urothelial carcinoma.",
    "PET-CT reveals FDG-avid mass in the pancreas; EUS-guided biopsy confirms pancreatic neuroendocrine tumor.",
    "Young female with a breast lump; core biopsy reveals phyllodes tumor with malignant potential.",
    "Colonoscopy shows a stenosing lesion in the descending colon; biopsy confirms signet-ring cell carcinoma.",
    "Patient with dysphagia and weight loss; esophagogastroduodenoscopy reveals an esophageal squamous cell carcinoma.",
    "MRI pelvis shows a large rectal mass with regional lymph node involvement; biopsy confirms adenocarcinoma.",
    "Elevated chromogranin A and a pancreatic mass on CT; biopsy suggests pancreatic neuroendocrine tumor.",
    "Patient with a scalp lesion; excision biopsy confirms basal cell carcinoma with perineural invasion.",
    "Chest X-ray shows a mediastinal mass; biopsy reveals thymoma in a patient with myasthenia gravis.",
    "Ultrasound shows a thyroid nodule with microcalcifications; FNA confirms medullary thyroid carcinoma.",
    "Patient with persistent back pain; MRI reveals a sacral mass; biopsy confirms chordoma.",
    "CT abdomen shows a retroperitoneal mass; biopsy reveals liposarcoma with dedifferentiated components.",
    "Patient with a history of BRCA2 mutation; MRI shows a pancreatic mass; biopsy confirms intraductal papillary mucinous neoplasm.",
    "Colonoscopy reveals a cecal mass; biopsy confirms mucinous adenocarcinoma with KRAS mutation.",
    "Patient with hemoptysis and a smoking history; CT shows a cavitating lung mass; biopsy confirms squamous cell carcinoma.",
    "Breast MRI shows a non-mass enhancement; biopsy reveals ductal carcinoma in situ with microinvasion.",
    "Elevated PSA and a palpable prostate nodule; biopsy confirms adenocarcinoma with Gleason 4+3 pattern.",
    "Patient with abdominal pain and jaundice; MRCP shows a bile duct mass; biopsy confirms cholangiocarcinoma.",
    "Chest CT shows a pleural effusion and mass; thoracentesis reveals malignant cells suggestive of mesothelioma.",
    "Ultrasound shows a hypoechoic liver lesion; biopsy confirms metastatic colorectal cancer.",
    "Patient with a neck mass and hoarseness; biopsy confirms anaplastic thyroid carcinoma.",
    "Colonoscopy reveals a polyp in the transverse colon; histopathology shows villous adenoma with high-grade dysplasia.",
    "MRI pelvis shows a uterine mass with lymphadenopathy; biopsy confirms serous endometrial carcinoma.",
    "Patient with a breast mass and skin ulceration; biopsy confirms Paget’s disease of the breast.",
    "CT-guided biopsy of a lung nodule reveals adenocarcinoma with ALK rearrangement.",
    "Patient with a family history of colon cancer; colonoscopy shows a sigmoid mass; biopsy confirms adenocarcinoma.",
    "Ultrasound reveals a complex adnexal mass; CA-125 elevated; biopsy confirms clear cell ovarian carcinoma.",
    "Patient with bone pain and elevated ALP; bone scan shows osteoblastic metastases from prostate cancer.",
    "Chest CT shows a spiculated mass in the right middle lobe; biopsy confirms large cell carcinoma.",
    "Patient with rectal bleeding; colonoscopy reveals a low rectal tumor; biopsy shows adenocarcinoma with MSI-H status.",
    "MRI brain shows multiple lesions; biopsy confirms metastatic melanoma with BRAF mutation.",
    "Patient with a breast lump and nipple retraction; biopsy confirms invasive ductal carcinoma, triple-negative.",
     # New samples for lymphoma
    "Patient presents with persistent night sweats, weight loss, and cervical lymphadenopathy; biopsy suggests non-Hodgkin lymphoma.",
    "PET-CT shows diffuse lymphadenopathy; excisional biopsy confirms follicular lymphoma.",
    "Patient with fatigue and splenomegaly; blood smear shows atypical lymphocytes; lymphoma suspected.",
    
    # New samples for leukemia
    "Patient with recurrent infections and fatigue; CBC shows elevated WBC and blasts; bone marrow biopsy confirms acute myeloid leukemia.",
    "Young male with easy bruising and petechiae; flow cytometry suggests acute lymphoblastic leukemia.",
    "Bone marrow aspiration reveals chronic lymphocytic leukemia in a patient with lymphadenopathy.",
    
    # New samples for pancreatic cancer
    "Patient with jaundice and epigastric pain; CT shows pancreatic head mass; CA 19-9 elevated.",
    "Endoscopic ultrasound reveals pancreatic tail lesion; biopsy confirms pancreatic ductal adenocarcinoma.",
    "Patient with weight loss and diabetes onset; MRI shows pancreatic mass with liver metastases.",
    
    # New samples for liver cancer
    "Patient with hepatitis C presents with right upper quadrant pain; ultrasound shows liver mass; AFP elevated.",
    "MRI reveals a 4 cm liver lesion with washout; biopsy confirms hepatocellular carcinoma.",
    "Patient with cirrhosis and ascites; CT shows multifocal liver lesions suggestive of liver cancer.",
        # Existing additional samples
    "Patient presents with persistent night sweats, weight loss, and cervical lymphadenopathy; biopsy suggests non-Hodgkin lymphoma.",
    "PET-CT shows diffuse lymphadenopathy; excisional biopsy confirms follicular lymphoma.",
    "Patient with fatigue and splenomegaly; blood smear shows atypical lymphocytes; lymphoma suspected.",
    "Patient with recurrent infections and fatigue; CBC shows elevated WBC and blasts; bone marrow biopsy confirms acute myeloid leukemia.",
    "Young male with easy bruising and petechiae; flow cytometry suggests acute lymphoblastic leukemia.",
    "Bone marrow aspiration reveals chronic lymphocytic leukemia in a patient with lymphadenopathy.",
    "Patient with jaundice and epigastric pain; CT shows pancreatic head mass; CA 19-9 elevated.",
    "Endoscopic ultrasound reveals pancreatic tail lesion; biopsy confirms pancreatic ductal adenocarcinoma.",
    "Patient with weight loss and diabetes onset; MRI shows pancreatic mass with liver metastases.",
    "Patient with hepatitis C presents with right upper quadrant pain; ultrasound shows liver mass; AFP elevated.",
    "MRI reveals a 4 cm liver lesion with washout; biopsy confirms hepatocellular carcinoma.",
    "Patient with cirrhosis and ascites; CT shows multifocal liver lesions suggestive of liver cancer.",

    # New samples for lymphoma
    "Cervical lymph node enlargement with fever; biopsy confirms Hodgkin lymphoma.",
    "Patient with B symptoms and mediastinal mass; PET scan suggests lymphoma.",
    "Young adult with enlarged lymph nodes and weight loss; biopsy confirms diffuse large B-cell lymphoma.",
    "CT shows axillary lymphadenopathy; FNA suggests lymphoma; full biopsy pending.",
    "Patient with night sweats and pruritus; lymph node biopsy confirms Hodgkin lymphoma.",
    "PET-CT reveals hypermetabolic lymph nodes in the retroperitoneum; biopsy confirms lymphoma.",
    "Patient with fatigue and lymphadenopathy; excisional biopsy suggests mantle cell lymphoma.",

    # New samples for leukemia
    "Child with fatigue and bone pain; blood smear shows blasts; acute lymphoblastic leukemia diagnosed.",
    "Patient with gingival bleeding and fatigue; CBC suggests acute promyelocytic leukemia.",
    "Elderly patient with anemia and leukocytosis; bone marrow confirms chronic lymphocytic leukemia.",
    "Patient with recurrent fevers and pallor; bone marrow biopsy confirms acute myeloid leukemia.",
    "Young female with easy bruising; flow cytometry confirms B-cell acute lymphoblastic leukemia.",
    "Patient with splenomegaly and leukocytosis; BCR-ABL testing suggests chronic myeloid leukemia.",
    "Bone marrow aspiration shows atypical blasts; leukemia diagnosis confirmed.",

    # New samples for pancreatic cancer
    "Abdominal pain and elevated CA 19-9; CT confirms pancreatic adenocarcinoma.",
    "Patient with obstructive jaundice; ERCP shows pancreatic mass.",
    "Elderly patient with back pain and weight loss; CT reveals pancreatic body mass.",
    "Patient with steatorrhea and abdominal pain; EUS confirms pancreatic adenocarcinoma.",
    "CT abdomen shows pancreatic mass with vascular invasion; biopsy confirms malignancy.",
    "Patient with new-onset diabetes and weight loss; MRI suggests pancreatic cancer.",
    "Endoscopic biopsy reveals pancreatic neuroendocrine tumor; chromogranin A elevated.",

    # New samples for liver cancer
    "Elevated AFP in a patient with chronic liver disease; ultrasound suggests hepatocellular carcinoma.",
    "Patient with hepatitis B and jaundice; MRI shows liver mass with portal vein invasion.",
    "Ultrasound reveals liver lesion in a patient with cirrhosis; AFP elevated.",
    "CT shows hypervascular liver mass; biopsy confirms hepatocellular carcinoma.",
    "Patient with right upper quadrant pain and weight loss; MRI confirms liver cancer.",
    "Liver biopsy shows metastatic liver cancer in a patient with colorectal history.",
    "Patient with cirrhosis and elevated AFP; CT suggests multifocal hepatocellular carcinoma."

]